### ISSUE TITLE
Error during the test executing a job using Python SDK

### ISSUE THREAD

**Issue by wc117** [VolumeFi/paloma#1017]
I could create a job using Python SDK succesfully but when I tried to execute a job using Python SDK, I got error from LCD server.

This is updated Python SDK code.
https://github.com/VolumeFi/paloma.py/tree/features/add-scheduler-metadata

```Traceback (most recent call last):
  File "/home/wc117/Workspace/paloma.py/integration_tests/job_scheduler.py", line 67, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/wc117/Workspace/paloma.py/integration_tests/job_scheduler.py", line 53, in main
    result = await paloma.job_scheduler.execute_job(test1, job_id, payload, creator, signers)
  File "/home/wc117/Workspace/paloma.py/venv/lib/python3.10/site-packages/paloma_sdk/client/lcd/api/scheduler.py", line 94, in execute_job
    execute_tx = await wallet.create_and_sign_tx(
  File "/home/wc117/Workspace/paloma.py/venv/lib/python3.10/site-packages/paloma_sdk/client/lcd/wallet.py", line 54, in create_and_sign_tx
    tx=(await self.create_tx(options)),
  File "/home/wc117/Workspace/paloma.py/venv/lib/python3.10/site-packages/paloma_sdk/client/lcd/wallet.py", line 40, in create_tx
    return await self.lcd.tx.create(sigOpt, options)
  File "/home/wc117/Workspace/paloma.py/venv/lib/python3.10/site-packages/paloma_sdk/client/lcd/api/tx.py", line 175, in create
    opt.fee = await BaseAsyncAPI._try_await(self.estimate_fee(signer_data, opt))
  File "/home/wc117/Workspace/paloma.py/venv/lib/python3.10/site-packages/paloma_sdk/client/lcd/api/_base.py", line 19, in _try_await
    return await aw
  File "/home/wc117/Workspace/paloma.py/venv/lib/python3.10/site-packages/paloma_sdk/client/lcd/api/tx.py", line 219, in estimate_fee
    gas = str(await super()._try_await(self.estimate_gas(tx, opt)))
  File "/home/wc117/Workspace/paloma.py/venv/lib/python3.10/site-packages/paloma_sdk/client/lcd/api/_base.py", line 19, in _try_await
    return await aw
  File "/home/wc117/Workspace/paloma.py/venv/lib/python3.10/site-packages/paloma_sdk/client/lcd/api/tx.py", line 232, in estimate_gas
    res = await self._c._post(
  File "/home/wc117/Workspace/paloma.py/venv/lib/python3.10/site-packages/paloma_sdk/client/lcd/lcdclient.py", line 136, in _post
    raise LCDResponseError(message=result.get("message"), response=response)
paloma_sdk.exceptions.LCDResponseError: Status 500 - recovered: runtime error: invalid memory address or nil pointer dereference
stack:
goroutine 2463364 [running]:
runtime/debug.Stack()
	/snap/go/10426/src/runtime/debug/stack.go:24 +0x5e
github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func3({0x2694320, 0x4d7d7c0})
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/baseapp/recovery.go:71 +0x25
github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func5({0x2694320?, 0x4d7d7c0?})
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/baseapp/recovery.go:39 +0x2d
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x2694320, 0x4d7d7c0}, 0xc002584990?)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/baseapp/recovery.go:28 +0x2f
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x2694320, 0x4d7d7c0}, 0x2d?)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/baseapp/recovery.go:33 +0x53
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/baseapp/baseapp.go:641 +0xfe
panic({0x2694320?, 0x4d7d7c0?})
	/snap/go/10426/src/runtime/panic.go:920 +0x270
github.com/palomachain/paloma/x/scheduler/keeper.msgServer.ExecuteJob({{0x36d9e90?, 0xc000e03420?}}, {0x36ced38?, 0xc03f55e9c0?}, 0xc04b4457a0)
	/root/gh_ci_src/paloma/x/scheduler/keeper/msg_server_execute_job.go:17 +0x2a7
github.com/palomachain/paloma/x/scheduler/types._Msg_ExecuteJob_Handler.func1({0x36ced38, 0xc03f55e9c0}, {0x29f9f20?, 0xc04b4457a0})
	/root/gh_ci_src/paloma/x/scheduler/types/tx.pb.go:401 +0x72
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x36ce6f8, 0xc03ac458c0}, {0xc050302578?, 0x41fb45?}, 0x2a0?, 0xc05b863188)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/baseapp/msg_service_router.go:118 +0x93
github.com/palomachain/paloma/x/scheduler/types._Msg_ExecuteJob_Handler({0x28798c0?, 0xc001215b20}, {0x36ce6f8, 0xc03ac458c0}, 0x3163d28, 0xc09a6e1020)
	/root/gh_ci_src/paloma/x/scheduler/types/tx.pb.go:403 +0x135
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x36ce768, 0x4f033c0}, {0x36e4160, 0xc00722c540}, {{0xb, 0x0}, {0xc0335a4648, 0x11}, 0x7e993a, {0x2351acf7, ...}, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/baseapp/msg_service_router.go:139 +0x343
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x36ce768, 0x4f033c0}, {0x36e4160, 0xc00722c540}, {{0xb, 0x0}, {0xc0335a4648, 0x11}, 0x7e993a, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/baseapp/baseapp.go:800 +0x271
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc0010203c0, 0x2, {0xc020dd29c0, 0x182, 0x1a0})
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/baseapp/baseapp.go:743 +0xe65
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/baseapp/test_helpers.go:25
github.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x36e56e0, 0xc012c175e0}, 0x0, {0xc000cd9350, 0x11}, {0x36f04f8, 0xc001044130}, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/x/auth/tx/service.go:132 +0x129
github.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler.func1({0x36ced38, 0xc08fce2bd0}, {0x2974540?, 0xc09a6e04a0})
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/types/tx/service.pb.go:1423 +0x72
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func1({0x36ced38, 0xc0539f1620}, {0x2974540, 0xc09a6e04a0}, 0xc09a6e04c0?, 0xc05b862720)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/baseapp/grpcserver.go:68 +0x391
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2.ChainUnaryServer.func1.1.1({0x36ced38?, 0xc0539f1620?}, {0x2974540?, 0xc09a6e04a0?})
	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x37
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1({0x36ced38?, 0xc0539f1620?}, {0x2974540?, 0xc09a6e04a0?}, 0x274eb60?, 0xc09a6e04c0?)
	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:33 +0xb0
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2.ChainUnaryServer.func1.1.1({0x36ced38?, 0xc0539f1620?}, {0x2974540?, 0xc09a6e04a0?})
	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x37
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2.ChainUnaryServer.func1({0x36ced38, 0xc0539f1620}, {0x2974540, 0xc09a6e04a0}, 0xc0025079d0?, 0x4223e5?)
	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xb5
github.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x29417a0?, 0xc000db6000}, {0x36ced38, 0xc0539f1620}, 0xc01d7272d0, 0xc0539f16b0)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/types/tx/service.pb.go:1425 +0x135
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2({0x29417a0, 0xc000db6000}, {0x36ced38, 0xc0539f1620}, 0x2a0f0a0?, 0xc020a219e0?)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/baseapp/grpcserver.go:82 +0x112
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001021860, {0x36e0d60, 0xc017b6b040}, 0xc020a219e0, 0xc01eed0b10, 0xc000e03b20, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc001021860, {0x36e0d60, 0xc017b6b040}, 0xc020a219e0, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/root/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 630
	/root/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:997 +0x145
: panic [cosmos/cosmos-sdk@v0.47.4/baseapp/recovery.go:69] With gas wanted: '18446744073709551615' and gas used: '27499' 
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2ba96aebf0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f2ba96a58a0>, 94250.632)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f2ba96aec50>```

**Comment by byte-bandit** [comment]
@wc117 

1. Which version of Paloma are you testing against? 
2. `sender` and `creator` are expected to be in the form of Bech32 `paloma...` - can you confirm you're setting those in the correct format?

**Comment by wc117** [comment]
1. I interacted with LCD server endpoint. So it will depend on the Paloma version of lcd.testnet.palomaswap.com.
2. sender is "paloma1cyyzpxplxdzkeea7kwsydadg87357qna8rgwj8", signers are ["paloma1cyyzpxplxdzkeea7kwsydadg87357qna8rgwj8"]
@byte-bandit

**Comment by byte-bandit** [comment]
@wc117 Are you able to run the tests against the current master version of Paloma on your local node? I fixed a bug this week in the handler for this message that would result in a `nil` panic, but it hasn't been deployed to main net yet.

**Comment by taariq** [comment]
@byte-bandit enabling lcd with paloma master requires lcd server installation. Here's the setup https://www.notion.so/volumefi/Basic-Server-Setup-58988071b6a5428eac3c2310329bafa7#66400ba32e50419d90ecb8ff70f1957f. Will you add this to one of our pviate testnet nodes? Then maybe @wc117 can build against it?

**Comment by byte-bandit** [comment]
@wc117 @taariq As far as I can tell, the tests are simply running the `create job` and `execute job` commands. Is there anything special about the node that you need for this to work? If not, there's a few things you could do. Either clone the Paloma repo yourself and target the public testnet network, or use private testnet which is currently running the latest mater as well.

**Comment by taariq** [comment]
@byte-bandit we need to set the private testnet nodes with 1 lcd server.

- Enable api server in .paloma/config/app.toml
- Change .paloma/config/app.toml and.paloma/config/ config.toml to switch localhost and 127.0.0.1 to 0.0.0.0
- Give @wc117 the hostname for the lcd server and he can test the SDK against the current private testnet. 

FYI @rootedbox @verabehr am I missing anything here?

**Comment by byte-bandit** [comment]
@taariq What exactly is an LCD server anyway? Do you mean enabling public ingress for one of the nodes so they can be reached from outside, or are you referring to something else?

**Comment by taariq** [comment]
LCD is acronym for another acronym API server. Once we enable the API endpoint, and provide a hostname, William can target that with the SDK.

**Comment by byte-bandit** [comment]
@taariq Weird. Where does this acronym come from, do you know? 

On the other side, since the underlaying issue of this has already been fixed, I'm going to close this issue. The nodes on test net are running with their API exposed, a simple port forwarding to the machine should be enough to run tests against it.
