### ISSUE TITLE
BUG: Stop Bot Button Fails for CurveBot Leverage Lending with Error: value out-of-bounds (argument=null, value="-332505238092939600000", code=INVALID_ARGUMENT, version=abi/5.7.0)

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1070]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

BUG: Stop Bot Button Fails for CurveBot Leverage Lending with Error: 

mybots-a17e16ac89df0734.js:1 args (3) [Array(1), Array(1), Array(1)]
mybots-a17e16ac89df0734.js:1 Preparing transaction hash...
mybots-a17e16ac89df0734.js:1 Estimating gas...
mybots-a17e16ac89df0734.js:1 Error: value out-of-bounds (argument=null, value="-332505238092939600000", code=INVALID_ARGUMENT, version=abi/5.7.0)
    at f.makeError (_app-a6760d04256e4325.js:1:189313)
    at f.throwError (_app-a6760d04256e4325.js:1:189427)
    at f.throwArgumentError (_app-a6760d04256e4325.js:1:189482)
    at k._throwError (_app-a6760d04256e4325.js:1:29603)
    at k.encode (_app-a6760d04256e4325.js:1:26504)
    at _app-a6760d04256e4325.js:1:23222
    at Array.forEach (<anonymous>)
    at h (_app-a6760d04256e4325.js:1:23095)
    at f.encode (_app-a6760d04256e4325.js:1:24676)
    at _app-a6760d04256e4325.js:1:23153

Loom: https://www.loom.com/share/f77457b2dae147d498c372aeee068647

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/curve-leverage-lending-bot-vyper/pull/3#pullrequestreview-1780991248
