### ISSUE TITLE
Make nest service api more resilient

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1080]
1. Add this to Uptime for tracking failure
2. Add auto-recover if it fails
3. Provide logs for source of failure. Why is this happening?

**Comment by rootedbox** [comment]
1. done
2. https://github.com/palomachain/paloma-nest-service/pull/79
3. 
```
SyntaxError: Unexpected token e in JSON at position 1632610
Dec 12 16:26:25 bots-server start.sh[3990385]:     at JSON.parse (<anonymous>)
Dec 12 16:26:25 bots-server start.sh[3990385]:     at exports.getTokenJson (/home/rootedbox/app/paloma-nest-service/app/services/TokenJson.js:18:19)
Dec 12 16:26:25 bots-server start.sh[3990385]:     at exports.getCoinInfo (/home/rootedbox/app/paloma-nest-service/app/services/CoinGecko.js:26:23)
Dec 12 16:26:25 bots-server start.sh[3990385]:     at exports.getTokenMarketData (/home/rootedbox/app/paloma-nest-service/app/controllers/TokenController.js:44:17)
Dec 12 16:26:25 bots-server start.sh[3990385]:     at Layer.handle [as handle_request] (/home/rootedbox/app/paloma-nest-service/node_modules/express/lib/router/layer.js:95:5)
Dec 12 16:26:25 bots-server start.sh[3990385]:     at next (/home/rootedbox/app/paloma-nest-service/node_modules/express/lib/router/route.js:144:13)
Dec 12 16:26:25 bots-server start.sh[3990385]:     at Route.dispatch (/home/rootedbox/app/paloma-nest-service/node_modules/express/lib/router/route.js:114:3)
Dec 12 16:26:25 bots-server start.sh[3990385]:     at Layer.handle [as handle_request] (/home/rootedbox/app/paloma-nest-service/node_modules/express/lib/router/layer.js:95:5)
Dec 12 16:26:25 bots-server start.sh[3990385]:     at /home/rootedbox/app/paloma-nest-service/node_modules/express/lib/router/index.js:284:15
Dec 12 16:26:25 bots-server start.sh[3990385]:     at Function.process_params (/home/rootedbox/app/paloma-nest-service/node_modules/express/lib/router/index.js:346:12) gecko.json
Dec 12 16:26:25 bots-server start.sh[3990385]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise >
Dec 12 16:26:25 bots-server start.sh[3990385]: TypeError: geckoTokens is not iterable
```

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/paloma-nest-service/pull/79
