### ISSUE TITLE
EURO OFF-RAMP BUG: SyntaxError: Cannot convert 1.119660104777693456667e+21 to a BigInt

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1089]
When trying to use 

contentScript.bundle.js:1 Content script works!
contentScript.bundle.js:1 ===> FROM THE PRINT MODULE: Using the 'printLine' function from the Print Module
5392-62fb692d3744a9ec.js:1 CURVE-JS IS CONNECTED TO NETWORK: {name: 'MAINNET', chainId: 1}
euros-7d4872e23027fcc5.js:1 SyntaxError: Cannot convert 1.119660104777693456667e+21 to a BigInt (at _app-bcd92ab1a23d3f14.js:1123:33592)
    at BigInt (<anonymous>)
    at l (_app-bcd92ab1a23d3f14.js:1123:33592)
    at signed (_app-bcd92ab1a23d3f14.js:1123:22106)
    at e (_app-bcd92ab1a23d3f14.js:1123:22130)
    at r.params (_app-bcd92ab1a23d3f14.js:1123:22877)
    at d (_app-bcd92ab1a23d3f14.js:1123:22913)
    at u (_app-bcd92ab1a23d3f14.js:1123:24217)
    at D (_app-bcd92ab1a23d3f14.js:1089:110973)
    at Object.readContract (_app-bcd92ab1a23d3f14.js:1090:5765)
    at rU (_app-bcd92ab1a23d3f14.js:1093:14245)

![Image](https://github.com/VolumeFi/paloma/assets/701864/285bf57b-a7fe-4ed6-a103-59c27789f45a)

**Comment by taariq** [comment]
@jamie088 also this error 
rpc.walletconnect.com/v1/?chainId=eip155:1&projectId=b790153c46fe59c25875a033a6c378ed:1 
               
       Failed to load resource: the server responded with a status of 502 ()
curve-leverage-lending-43988255bfdc727e.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'weth')
    at eX (curve-leverage-lending-43988255bfdc727e.js:1:21117)

**Comment by jamie088** [comment]
@verabehr Not started this ticket yet. Is this a top priority ticket now?

**Comment by verabehr** [comment]
@jamie088 we want all bugs on the live bots fixed before moving to the new Gnosis features.

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/299
