### ISSUE TITLE
BUG: Twap Token Selection results in 404-Page not Found See Loom

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1112]
trying to use Curve TWAP results in error: Page Not Found.

Loom: https://www.loom.com/share/2b2971d0423a4c0bb45cb4020748d3a5?sid=7f75e54e-ac13-4827-a68e-6c6767a99d54

Error Logs:
5392-62fb692d3744a9ec.js:1 CURVE-JS IS CONNECTED TO NETWORK: {name: 'MAINNET', chainId: 1}
framework-a2363dd3c3dbe572.js:9 TypeError: Cannot read properties of undefined (reading 'raw')
    at 1446-60ac9af9cdf53073.js:1:2586
    at m (1446-60ac9af9cdf53073.js:1:2809)
    at ab (framework-a2363dd3c3dbe572.js:9:60870)
    at ud (framework-a2363dd3c3dbe572.js:9:72752)
    at i (framework-a2363dd3c3dbe572.js:9:120307)
    at oO (framework-a2363dd3c3dbe572.js:9:99059)
    at framework-a2363dd3c3dbe572.js:9:98926
    at oF (framework-a2363dd3c3dbe572.js:9:98933)
    at ox (framework-a2363dd3c3dbe572.js:9:95685)
    at oS (framework-a2363dd3c3dbe572.js:9:94240)
a5 @ framework-a2363dd3c3dbe572.js:9
a.componentDidCatch.t.callback @ framework-a2363dd3c3dbe572.js:9
lH @ framework-a2363dd3c3dbe572.js:9
uY @ framework-a2363dd3c3dbe572.js:9
e @ framework-a2363dd3c3dbe572.js:9
(anonymous) @ framework-a2363dd3c3dbe572.js:9
oI @ framework-a2363dd3c3dbe572.js:9
oS @ framework-a2363dd3c3dbe572.js:9
x @ framework-a2363dd3c3dbe572.js:33
T @ framework-a2363dd3c3dbe572.js:33
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
u @ framework-a2363dd3c3dbe572.js:33
M @ framework-a2363dd3c3dbe572.js:33
n.unstable_scheduleCallback @ framework-a2363dd3c3dbe572.js:33
ow @ framework-a2363dd3c3dbe572.js:9
ok @ framework-a2363dd3c3dbe572.js:9
aG @ framework-a2363dd3c3dbe572.js:9
(anonymous) @ curve-twap-ed6b38e54289202f.js:1

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/301#event-11293853377
