### ISSUE TITLE
Bug: Eur-Off-ramp bot attemps to reinsert tx and then fails to finish TWAPs with Balance XDAI on Gnosis Contract

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1130]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

1. Transaction for 20,514.909040445235889125($20,486.29)
Dai Stablecoin. https://etherscan.io/tx/0xaf7c6ebd7c0782b1d03e437030ae4c37124c24eee72446629ff14a4dd65f79d5

2. Vera identifies this error and Jason confirms that the script is attempting to reinsert the deposit transaction into the db, but the db complains because the tx is already inserted. See the error:

Dec 28 21:36:56 bots-server npm[1824892]: INSERT INTO deposits (deposit_id, token0, token1, amount0, amount1, depositor, number_trades, remaining_counts, interval, deposit_price, network_na>
Dec 28 21:36:56 bots-server npm[1824892]: ()
Dec 28 21:36:56 bots-server npm[1824892]: stderr: Traceback (most recent call last):
Dec 28 21:36:56 bots-server npm[1824892]: stderr:   File "/home/rootedbox/app/offramp-eure-bot-script/./bot-execute.py", line 257, in <module>
Dec 28 21:36:56 bots-server npm[1824892]: stderr:     asyncio.run(main())
Dec 28 21:36:56 bots-server npm[1824892]: stderr:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
Dec 28 21:36:56 bots-server npm[1824892]: stderr:     return loop.run_until_complete(main)
Dec 28 21:36:56 bots-server npm[1824892]: stderr:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
Dec 28 21:36:56 bots-server npm[1824892]: stderr:   File "/home/rootedbox/app/offramp-eure-bot-script/./bot-execute.py", line 252, in main
Dec 28 21:36:56 bots-server npm[1824892]: stderr:     await eure_bot(network)
Dec 28 21:36:56 bots-server npm[1824892]:   File "/home/rootedbox/app/offramp-eure-bot-script/./bot-execute.py", line 127, in eure_bot
Dec 28 21:36:56 bots-server npm[1824892]: stderr:     execute_with_retry(query)
Dec 28 21:36:56 bots-server npm[1824892]:   File "/home/rootedbox/app/offramp-eure-bot-script/./bot-execute.py", line 52, in execute_with_retry
Dec 28 21:36:56 bots-server npm[1824892]:     raise Exception(f"Failed to execute query after {max_attempts} attempts")
Dec 28 21:36:56 bots-server npm[1824892]: Exception: Failed to execute query after 5 attempts
Dec 28 21:36:56 bots-server npm[1824892]: stderr: Unclosed client session
Dec 28 21:36:56 bots-server npm[1824892]: client_session: <aiohttp.client.ClientSession object at 0x7f1d590abc10>
Dec 28 21:36:56 bots-server npm[1824892]: bot-execute.py script exited with code 1```

3. Jason bumped the block number to the number after his block and it started pulling in things. The TWAPs appear to start
https://gnosisscan.io/address/0x48afa99cd4166d89718cba46db7e1eeb99535b46#internaltx

4. However, there is still a balance of 9,457.984049908251004324 xDAI and Michael has shared that the TWAPs are no longe processing

5. We suspect that the funds are stuck on the contracts because of this database issue, but do not know how to get those funds off the contract and over to the user's account.

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/offramp-eure-bot/commit/9e88de9f89c88a465bfcd443457056ceb99e8c49
