### ISSUE TITLE
Curve lending - unhealthy bots are not triggered for repayment

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1203]
There seem to be 2 issues. 

1. The tracking_price does not actually contain the accurate loan health (Note, the FE doesn't seem to use it, so I'm not sure if this is actually a problem)
2. There is one leverage bot that should have been repaid, but hasn't  (see bold column in sheet)
3. There is one lending bot that should have been repaid, but hasn't  (see bold column in sheet)

https://docs.google.com/spreadsheets/d/1E_M4t_D5vHj9cdQR4qj4DJQfHRQRaBZgVjn4AeazhN0/edit?usp=sharing

**Comment by verabehr** [comment]
@rootedbox on curve lending we're getting this error: 

```
Jan 19 15:24:03 bots-server start.sh[2708234]: CURVE-JS IS CONNECTED TO NETWORK: { name: 'MAINNET', chainId: 1 }
Jan 19 15:24:09 bots-server start.sh[2708234]: ReferenceError: bot_info_repays is not defined
Jan 19 15:24:09 bots-server start.sh[2708234]:     at executeWithdraw (file:///home/rootedbox/app/curve-lending-bot/curve-lending.js:496:5)
Jan 19 15:24:09 bots-server start.sh[2708234]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 19 15:24:09 bots-server start.sh[2708234]:     at async getNewBlocks (file:///home/rootedbox/app/curve-lending-bot/curve-lending.js:368:5)
Jan 19 15:24:09 bots-server start.sh[2708234]:     at async Timeout.getLastBlock [as _onTimeout] (file:///home/rootedbox/app/curve-lending-bot/curve-lending.js:123:13)
Jan 19 15:24:17 bots-server start.sh[2708234]: Row with id 697 updated successfully.
```

**Comment by verabehr** [comment]
```Jan 19 17:27:08 bots-server start.sh[2862975]: ReferenceError: wallet is not defined
Jan 19 17:27:08 bots-server start.sh[2862975]:     at executeWithdraw (file:///home/rootedbox/app/curve-lending-bot/curve-lending.js:515:13)
Jan 19 17:27:08 bots-server start.sh[2862975]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 19 17:27:08 bots-server start.sh[2862975]:     at async getNewBlocks (file:///home/rootedbox/app/curve-lending-bot/curve-lending.js:368:5)
Jan 19 17:27:08 bots-server start.sh[2862975]:     at async Timeout.getLastBlock [as _onTimeout] (file:///home/rootedbox/app/curve-lending-bot/curve-lending.js:123:13)```

**Comment by verabehr** [comment]
Curve leverage looks good, but we're still not repaying curve lending bots.

**Comment by verabehr** [comment]
Curve lending bot is not repaid, but we're getting errors on withdraw

```
Jan 29 21:35:44 bots-server start.sh[3819551]: executeWithdraw: TypeError: Cannot read properties of undefined (reading 'contract')
Jan 29 21:35:44 bots-server start.sh[3819551]:     at Curve.<anonymous> (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:561:107)
Jan 29 21:35:44 bots-server start.sh[3819551]:     at step (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:43:23)
Jan 29 21:35:44 bots-server start.sh[3819551]:     at Object.next (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:24:53)
Jan 29 21:35:44 bots-server start.sh[3819551]:     at fulfilled (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:15:58)
Jan 29 21:35:44 bots-server start.sh[3819551]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

```
Jan 29 21:35:51 bots-server start.sh[3819551]: executeWithdraw: TypeError: invalid value for Contract target (argument="target", value=null, code=INVALID_ARGUMENT, version=6.9.1)
Jan 29 21:35:51 bots-server start.sh[3819551]:     at makeError (file:///home/rootedbox/app/curve-lending-bot/node_modules/ethers/lib.esm/utils/errors.js:117:21)
Jan 29 21:35:51 bots-server start.sh[3819551]:     at assert (file:///home/rootedbox/app/curve-lending-bot/node_modules/ethers/lib.esm/utils/errors.js:143:15)
Jan 29 21:35:51 bots-server start.sh[3819551]:     at assertArgument (file:///home/rootedbox/app/curve-lending-bot/node_modules/ethers/lib.esm/utils/errors.js:154:5)
Jan 29 21:35:51 bots-server start.sh[3819551]:     at new BaseContract (file:///home/rootedbox/app/curve-lending-bot/node_modules/ethers/lib.esm/contract/contract.js:541:9)
Jan 29 21:35:51 bots-server start.sh[3819551]:     at new Contract (file:///home/rootedbox/app/curve-lending-bot/node_modules/ethers/lib.esm/contract/contract.js:951:8)
Jan 29 21:35:51 bots-server start.sh[3819551]:     at Curve.setContract (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:1102:23)
Jan 29 21:35:51 bots-server start.sh[3819551]:     at Curve.<anonymous> (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:1026:30)
Jan 29 21:35:51 bots-server start.sh[3819551]:     at step (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:43:23)
Jan 29 21:35:51 bots-server start.sh[3819551]:     at Object.next (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:24:53)
Jan 29 21:35:51 bots-server start.sh[3819551]:     at fulfilled (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:15:58)
Jan 29 21:35:51 bots-server start.sh[3819551]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
Jan 29 21:35:51 bots-server start.sh[3819551]:   code: 'INVALID_ARGUMENT',
Jan 29 21:35:51 bots-server start.sh[3819551]:   argument: 'target',
Jan 29 21:35:51 bots-server start.sh[3819551]:   value: undefined,
Jan 29 21:35:51 bots-server start.sh[3819551]:   shortMessage: 'invalid value for Contract target'
Jan
```

**Comment by rootedbox** [comment]
@verabehr @wc117 what I'm currently sending and what I'm getting back in curve-lending

https://gist.github.com/rootedbox/648555e1a98541eeb386cfb8d73331f9

**Comment by verabehr** [comment]
potentially caused by a CW bug

**Comment by taariq** [comment]
Closing as won't ship
