### ISSUE TITLE
Errors in curve lending bot logs

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1224]
potentially related to https://github.com/VolumeFi/paloma/issues/1203

```Jan 26 14:16:13 bots-server start.sh[2458404]:     data: {
Jan 26 14:16:13 bots-server start.sh[2458404]:       code: 2,
Jan 26 14:16:13 bots-server start.sh[2458404]:       message: "failed to execute message; message index: 0: Error parsing into type curve_lending_bot_cw::msg::ExecuteMsg: unknown field `add_collateral`, >
Jan 26 14:16:13 bots-server start.sh[2458404]:       details: []
Jan 26 14:16:13 bots-server start.sh[2458404]:     }
```

```
Jan 26 14:16:33 bots-server start.sh[2458404]: bot_info_add_capital: Error: Request failed with status code 500
Jan 26 14:16:33 bots-server start.sh[2458404]:     at createError (/home/rootedbox/app/curve-lending-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/core/createError.js:16:15)
Jan 26 14:16:33 bots-server start.sh[2458404]:     at settle (/home/rootedbox/app/curve-lending-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/core/settle.js:17:12)
Jan 26 14:16:33 bots-server start.sh[2458404]:     at IncomingMessage.handleStreamEnd (/home/rootedbox/app/curve-lending-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/adapters/http.js:32>
Jan 26 14:16:33 bots-server start.sh[2458404]:     at IncomingMessage.emit (node:events:525:35)
Jan 26 14:16:33 bots-server start.sh[2458404]:     at IncomingMessage.emit (node:domain:489:12)
Jan 26 14:16:33 bots-server start.sh[2458404]:     at endReadableNT (node:internal/streams/readable:1359:12)
Jan 26 14:16:33 bots-server start.sh[2458404]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
Jan 26 14:16:33 bots-server start.sh[2458404]:   config: {
Jan 26 14:16:33 bots-server start.sh[2458404]:     transitional: {
Jan 26 14:16:33 bots-server start.sh[2458404]:       silentJSONParsing: true,
Jan 26 14:16:33 bots-server start.sh[2458404]:       forcedJSONParsing: true,
Jan 26 14:16:33 bots-server start.sh[2458404]:       clarifyTimeoutError: false
Jan 26 14:16:33 bots-server start.sh[2458404]:     },
```

```
Jan 26 14:16:40 bots-server start.sh[2458404]: executeWithdraw: Error: Coin with address 'crv' is not available
Jan 26 14:16:40 bots-server start.sh[2458404]:     at _getCoinAddresses (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/utils.js:161:19)
Jan 26 14:16:40 bots-server start.sh[2458404]:     at file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/router.js:716:22
Jan 26 14:16:40 bots-server start.sh[2458404]:     at step (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/router.js:43:23)
Jan 26 14:16:40 bots-server start.sh[2458404]:     at Object.next (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/router.js:24:53)
Jan 26 14:16:40 bots-server start.sh[2458404]:     at file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/router.js:18:71
Jan 26 14:16:40 bots-server start.sh[2458404]:     at new Promise (<anonymous>)
Jan 26 14:16:40 bots-server start.sh[2458404]:     at __awaiter (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/router.js:14:12)
Jan 26 14:16:40 bots-server start.sh[2458404]:     at Object.getBestRouteAndOutput (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/router.js:711:86)
Jan 26 14:16:40 bots-server start.sh[2458404]:     at executeWithdraw (file:///home/rootedbox/app/curve-lending-bot/curve-lending.js:467:62)
Jan 26 14:16:40 bots-server start.sh[2458404]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 26 14:16:40 bots-server start.sh[2458404]:     at async getNewBlocks (file:///home/rootedbox/app/curve-lending-bot/curve-lending.js:368:5)
Jan 26 14:16:40 bots-server start.sh[2458404]:     at async Timeout.getLastBlock [as _onTimeout] (file:///home/rootedbox/app/curve-lending-bot/curve-lending.js:123:13)
Jan 26 14:16:40 bots-server start.sh[2458404]: bot_info_add_capital: Error: Request failed with status code 500
Jan 26 14:16:40 bots-server start.sh[2458404]:     at createError (/home/rootedbox/app/curve-lending-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/core/createError.js:16:15)
Jan 26 14:16:40 bots-server start.sh[2458404]:     at settle (/home/rootedbox/app/curve-lending-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/core/settle.js:17:12)
Jan 26 14:16:40 bots-server start.sh[2458404]:     at IncomingMessage.handleStreamEnd (/home/rootedbox/app/curve-lending-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/adapters/http.js:32>
Jan 26 14:16:40 bots-server start.sh[2458404]:     at IncomingMessage.emit (node:events:525:35)
Jan 26 14:16:40 bots-server start.sh[2458404]:     at IncomingMessage.emit (node:domain:489:12)
Jan 26 14:16:40 bots-server start.sh[2458404]:     at endReadableNT (node:internal/streams/readable:1359:12)
Jan 26 14:16:40 bots-server start.sh[2458404]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
Jan 26 14:16:40 bots-server start.sh[2458404]:   config: {
Jan 26 14:16:40 bots-server start.sh[2458404]:     transitional: {
Jan 26 14:16:40 bots-server start.sh[2458404]:       silentJSONParsing: true,
Jan 26 14:16:40 bots-server start.sh[2458404]:       forcedJSONParsing: true,
Jan 26 14:16:40 bots-server start.sh[2458404]:       clarifyTimeoutError: false
Jan 26 14:16:40 bots-server start.sh[2458404]:     },
```

```
Jan 26 14:23:20 bots-server start.sh[2458404]: executeWithdraw: TypeError: Cannot read properties of undefined (reading 'contract')
Jan 26 14:23:20 bots-server start.sh[2458404]:     at Curve.<anonymous> (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:561:107)
Jan 26 14:23:20 bots-server start.sh[2458404]:     at step (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:43:23)
Jan 26 14:23:20 bots-server start.sh[2458404]:     at Object.next (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:24:53)
Jan 26 14:23:20 bots-server start.sh[2458404]:     at fulfilled (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:15:58)
Jan 26 14:23:20 bots-server start.sh[2458404]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

```
Jan 26 14:23:22 bots-server start.sh[2458404]: executeWithdraw: TypeError: invalid value for Contract target (argument="target", value=null, code=INVALID_ARGUMENT, version=6.9.1)
Jan 26 14:23:22 bots-server start.sh[2458404]:     at makeError (file:///home/rootedbox/app/curve-lending-bot/node_modules/ethers/lib.esm/utils/errors.js:117:21)
Jan 26 14:23:22 bots-server start.sh[2458404]:     at assert (file:///home/rootedbox/app/curve-lending-bot/node_modules/ethers/lib.esm/utils/errors.js:143:15)
Jan 26 14:23:22 bots-server start.sh[2458404]:     at assertArgument (file:///home/rootedbox/app/curve-lending-bot/node_modules/ethers/lib.esm/utils/errors.js:154:5)
Jan 26 14:23:22 bots-server start.sh[2458404]:     at new BaseContract (file:///home/rootedbox/app/curve-lending-bot/node_modules/ethers/lib.esm/contract/contract.js:541:9)
Jan 26 14:23:22 bots-server start.sh[2458404]:     at new Contract (file:///home/rootedbox/app/curve-lending-bot/node_modules/ethers/lib.esm/contract/contract.js:951:8)
Jan 26 14:23:22 bots-server start.sh[2458404]:     at Curve.setContract (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:1102:23)
Jan 26 14:23:22 bots-server start.sh[2458404]:     at Curve.<anonymous> (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:1026:30)
Jan 26 14:23:22 bots-server start.sh[2458404]:     at step (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:43:23)
Jan 26 14:23:22 bots-server start.sh[2458404]:     at Object.next (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:24:53)
Jan 26 14:23:22 bots-server start.sh[2458404]:     at fulfilled (file:///home/rootedbox/app/curve-lending-bot/node_modules/@curvefi/api/lib/curve.js:15:58)
Jan 26 14:23:22 bots-server start.sh[2458404]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
Jan 26 14:23:22 bots-server start.sh[2458404]:   code: 'INVALID_ARGUMENT',
Jan 26 14:23:22 bots-server start.sh[2458404]:   argument: 'target',
Jan 26 14:23:22 bots-server start.sh[2458404]:   value: undefined,
Jan 26 14:23:22 bots-server start.sh[2458404]:   shortMessage: 'invalid value for Contract target'
```

**Comment by verabehr** [comment]
https://github.com/VolumeFi/curve-lending-bot/commit/ed86cf14aa657caa8bfd6f5a9d9430a32937d6a2
