### ISSUE TITLE
BUG: Curve TWAP stalls halfway through the transaction. User cancels Bot Service gives 502

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1290]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

BUG: Curve TWAP stalls halfway through the transaction. 
[Curve TWAP:](https://etherscan.io/tx/0xd1e7760313a3fbc7c70bf89ace711bc14b43613aeba65bbf26076da215f7aba7)

It appears the TWAP bot stopped at 7:04AM PT

Monitor: check.bots.palomachain.com/curve_twap_bot
Checked URL: GET [https://check.bots.palomachain.com/curve_twap_bot/](https://uptime.betterstack.com/ahoy/messages/gWWIzSxDCxWAXN2XJwpxGZBw18iDvP8W/click?signature=fec7908db1c965d3b8ac5831d74be2debfdd4135&url=https%3A%2F%2Fcheck.bots.palomachain.com%2Fcurve_twap_bot%2F%3Futm_source%3Descalation_mailer%26utm_medium%3Demail%26utm_campaign%3Dstarted)
Cause: Status 502 Bad Gateway 502 Bad Gateway nginx/1.18.0 (Ubuntu)

It appears the TWAP bot RE-STARTED at 7:18AM AM PT
[https://check.bots.palomachain.com/curve_twap_bot/] [✅ Up] 200 - OK
Time (UTC): 2024-02-17 15:18:41.910

User canceled the transaction at 7:33AM PT
https://etherscan.io/tx/0x5796e7fa3e149af692b4f956a0f8abd1b1ec2ced4daa03bcc63d377718d670dc

Started at: 17 Feb 2024 at 04:58am HST
# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

Test Curve TWAP and check logs.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

 Curve TWAP does not stop.

**Comment by verabehr** [comment]
We got this error for at least 30 mins before the server restarted. I'm not sure why the server actually stopped and restarted

```
Feb 17 15:34:00 bots-server run.sh[3111072]: paloma_sdk.exceptions.LCDResponseError: Status 500 - failed to execute message; message index: 0: AllPending: execute wasm contract failed [!cosm!wasm/wasmd@v>
Feb 17 15:34:08 bots-server run.sh[3111411]: https://lcd.palomachain.com/cosmos/auth/v1beta1/accounts/paloma10dry4t7gr8rhd0khqcqyq95ytdh6vs8sjv84yj
Feb 17 15:34:08 bots-server run.sh[3111411]: Traceback (most recent call last):
Feb 17 15:34:08 bots-server run.sh[3111411]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 459, in <module>
Feb 17 15:34:08 bots-server run.sh[3111411]:     asyncio.run(main())
Feb 17 15:34:08 bots-server run.sh[3111411]:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
Feb 17 15:34:08 bots-server run.sh[3111411]:     return loop.run_until_complete(main)
Feb 17 15:34:08 bots-server run.sh[3111411]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
Feb 17 15:34:08 bots-server run.sh[3111411]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 454, in main
Feb 17 15:34:08 bots-server run.sh[3111411]:     await asyncio.gather(worker(), web_server())
Feb 17 15:34:08 bots-server run.sh[3111411]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 449, in worker
Feb 17 15:34:08 bots-server run.sh[3111411]:     await curve_bot(network)
Feb 17 15:34:08 bots-server run.sh[3111411]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 372, in curve_bot
Feb 17 15:34:08 bots-server run.sh[3111411]:     tx = await paloma_wallet.create_and_sign_tx(CreateTxOptions(msgs=[
Feb 17 15:34:08 bots-server run.sh[3111411]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/wallet.py", line 54, in create_and_sign_tx
Feb 17 15:34:08 bots-server run.sh[3111411]:     tx=(await self.create_tx(options)),
Feb 17 15:34:08 bots-server run.sh[3111411]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/wallet.py", line 40, in create_tx
Feb 17 15:34:08 bots-server run.sh[3111411]:     return await self.lcd.tx.create(sigOpt, options)
Feb 17 15:34:08 bots-server run.sh[3111411]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/api/tx.py", line 175, in create
Feb 17 15:34:08 bots-server run.sh[3111411]:     opt.fee = await BaseAsyncAPI._try_await(self.estimate_fee(signer_data, opt))
Feb 17 15:34:08 bots-server run.sh[3111411]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/api/_base.py", line 19, in _try_await
Feb 17 15:34:08 bots-server run.sh[3111411]:     return await aw
Feb 17 15:34:08 bots-server run.sh[3111411]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/api/tx.py", line 219, in estimate_fee
Feb 17 15:34:08 bots-server run.sh[3111411]:     gas = str(await super()._try_await(self.estimate_gas(tx, opt)))
Feb 17 15:34:08 bots-server run.sh[3111411]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/api/_base.py", line 19, in _try_await
Feb 17 15:34:08 bots-server run.sh[3111411]:     return await aw
Feb 17 15:34:08 bots-server run.sh[3111411]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/api/tx.py", line 232, in estimate_gas
Feb 17 15:34:08 bots-server run.sh[3111411]:     res = await self._c._post(
Feb 17 15:34:08 bots-server run.sh[3111411]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/lcdclient.py", line 136, in _post
Feb 17 15:34:08 bots-server run.sh[3111411]:     raise LCDResponseError(message=result.get("message"), response=response)
```

**Comment by taariq** [comment]
What is the balance of GRAIN on the wallet?

**Comment by taariq** [comment]
The TWAP wallet has GRAINS: https://paloma.explorers.guru/account/paloma10dry4t7gr8rhd0khqcqyq95ytdh6vs8sjv84yj

**Comment by taariq** [comment]
This is a Devops issue the.
