### ISSUE TITLE
BUG: Quicknode complaining too many requests more than 550/sec!

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1293]
We are sending more than 550 requests per second to Quicknode. We are unable to get the bot working.

7562-35264ab1fc96f3c5.js:1 e Error: could not coalesce error (error={ "code": -32012, "message": "credits limited to 550/sec" }, payload={ "id": 7, "jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": [ "latest", false ] }, code=UNKNOWN_ERROR, version=6.7.0)
    at o (5392-62fb692d3744a9ec.js:1:2178274)
    at aF.getRpcError (5392-62fb692d3744a9ec.js:1:340919)
    at 5392-62fb692d3744a9ec.js:1:334302
5392-62fb692d3744a9ec.js:1 
POST https://serene-divine-crater.quiknode.pro/ 429 (Too Many Requests)

**Comment by taariq** [comment]
This appears fixed. not seeing it again. Closing.
