### ISSUE TITLE
BUG: Moralis SDK Core Error: [C0006] Request failed: Network Error

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1318]
Testing: https://www.curvebot.fi/curve-leverage-lending/

contentScript.bundle.js:1 Content script works!
contentScript.bundle.js:1 ===> FROM THE PRINT MODULE: Using the 'printLine' function from the Print Module
6916-ec1e2a261749e8f6.js:1 CURVE-JS IS CONNECTED TO NETWORK: Object
_app-a8980f84eb85d281.js:1 sending message
contentScript.bundle.js:1 response connect wallet {status: false}
contentScript.bundle.js:1 responsed message {type: 'EXTERNAL_CONNECT_WALLET_RESPONSE', currentWallet: {…}, connectedChain: {…}}
1377-70f7acd4d00d6c6e.js:1 Moralis SDK Core Error: [C0006] Request failed: Network Error
    at e.makeError (https://www.curvebot.fi/_next/static/chunks/pages/_app-a8980f84eb85d281.js:1093:91498)
    at e.<anonymous> (https://www.curvebot.fi/_next/static/chunks/pages/_app-a8980f84eb85d281.js:1093:90951)
    at https://www.curvebot.fi/_next/static/chunks/pages/_app-a8980f84eb85d281.js:1093:77752
    at Object.throw (https://www.curvebot.fi/_next/static/chunks/pages/_app-a8980f84eb85d281.js:1093:77857)
    at s (https://www.curvebot.fi/_next/static/chunks/pages/_app-a8980f84eb85d281.js:1093:76634)
t @ 1377-70f7acd4d00d6c6e.js:1
await in t (async)
E @ 1377-70f7acd4d00d6c6e.js:1
e @ 1377-70f7acd4d00d6c6e.js:1
(anonymous) @ 1377-70f7acd4d00d6c6e.js:1
setTimeout (async)
(anonymous) @ 1377-70f7acd4d00d6c6e.js:1
uI @ framework-a2363dd3c3dbe572.js:9
oU @ framework-a2363dd3c3dbe572.js:9
(anonymous) @ framework-a2363dd3c3dbe572.js:9
oI @ framework-a2363dd3c3dbe572.js:9
oC @ framework-a2363dd3c3dbe572.js:9
r4 @ framework-a2363dd3c3dbe572.js:9
(anonymous) @ framework-a2363dd3c3dbe572.js:9
_app-a8980f84eb85d281.js:1093

**Comment by taariq** [comment]
Closing until it hurts.
