### ISSUE TITLE
Follow up on https://github.com/VolumeFi/paloma/issues/1542 - the wrong bot record was created

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1545]
- [ ] The wrong bot record was created. In the api it is listed as `juice_eth_curve`, but we're expecting `leverage_curve` 
- [ ] also need to confirm the withdraw block / that the user can withdraw their funds from this bot

```
{"deposit_id":"10","token0":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","token1":"0xf939e0a03fb07f59a73314e73794be0e57ac1b4e","amount0":"2994000000000000000","amount1":"41270907700069100000000","depositor":"0xcd2C0bB5DDEad5D0f27E97F42637835247E5F08B","deposit_price":"10278.19242","tracking_price":"9654.33264","expire":"33247318997","withdrawer":"0x79C9A765d865f949c18335321436fAAfa865B2e6","network_name":"ETH","dex_name":"curve","bot":"juice_eth_curve","number_trades":"5","remaining_counts":"4","interval":"30","contract":"0x34BC9970228b14A76ebF0A7f5a601001bBCA20C8","bot_type":"12","fees_charged":"0.05223062279655718","sent_to_mixpanel":"0","transaction_hash":"0x4eef2c5f77844b4151507ca4ff20cc8fd919ed8d29d5f8c99112fd0e2cfcf757","create_to_mixpanel":"0","created_at":"2024-03-24 22:23:38","gas_mixpanel":"0","leverage":"495","health_threshold":"200","deleverage_percentage":"5000","health":"303.11585355309603","coin_info":{"id":"crvusd","symbol":"crvusd","name":"crvUSD","platforms":{
```

**Comment by taariq** [comment]
@rootedbox the user is now getting the following error:

Hide TabsChats
Calls
Stories
SettingsChatsNew chatMore Actions

Mason Borda
2m
provider-bridge.js:1140  content: background > inpage: {"id":"tallyHo","jsonrpc":"2.0","result":{"method":"tally_getConfig","defaultWallet":true}} provider-bridge.js:1140  content: background > inpage: {"id":"tallyHo","jsonrpc":"2.0","result":{"method":"tally_getConfig","defaultWallet":true,"chainId":"0x1"}} injected.js:1 Uncaught TypeError: Cannot redefine property: ethereum     at Function.defineProperty (<anonymous>)     at qVn (injected.js:1:5025960)     at LVn (injected.js:1:5024975)     at injected.js:1:5033038     at injected.js:1:5033045 qVn @ injected.js:1 LVn @ injected.js:1 (anonymous) @ injected.js:1 (anonymous) @ injected.js:1 contentScript.bundle.js:1 Content script works! contentScript.bundle.js:1 ===> FROM THE PRINT MODULE: Using the 'printLine' function from the Print Module provider-bridge.js:1135  content: inpage > background: {"id":"0","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}} provider-bridge.js:1140  content: background > inpage: {"id":"0","jsonrpc":"2.0","result":["0x79c9a765d865f949c18335321436faafa865b2e6"]} provider-bridge.js:1135  content: inpage > background: {"id":"1","target":"tally-provider-bridge","request":{"method":"net_version","params":[]}} provider-bridge.js:1140  content: background > inpage: {"id":"1","jsonrpc":"2.0","result":"1"} provider-bridge.js:1135  content: inpage > background: {"id":"2","target":"tally-provider-bridge","request":{"method":"eth_chainId","params":[]}} provider-bridge.js:1140  content: background > inpage: {"id":"2","jsonrpc":"2.0","result":"0x1"} 6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: {name: 'MAINNET', chainId: 1} 6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: {name: 'MAINNET', chainId: 1} 6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: {name: 'MAINNET', chainId: 1} 6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: {name: 'MAINNET', chainId: 1} mybots/:1 Third-party cookie will be blocked. Learn more in the Issues tab. mybots/:1 Third-party cookie will be blocked. Learn more in the Issues tab. mybots/:1 Third-party cookie will be blocked. Learn more in the Issues tab. mybots/:1 Third-party cookie will be blocked. Learn more in the Issues tab. provider-bridge.js:1140  content: background > inpage: {"id":"tallyHo","jsonrpc":"2.0","result":{"method":"tally_getConfig","defaultWallet":true}} provider-bridge.js:1140  content: background > inpage: {"id":"tallyHo","jsonrpc":"2.0","result":{"method":"tally_getConfig","defaultWallet":true,"chainId":"0x1"}} provider-bridge.js:1135  content: inpage > background: {"id":"3","target":"tally-provider-bridge","request":{"method":"wallet_switchEthereumChain","params":[{"chainId":"0x1"}]}} provider-bridge.js:1140  content: background > inpage: {"id":"3","jsonrpc":"2.0","result":null} provider-bridge.js:1135  content: inpage > background: {"id":"4","target":"tally-provider-bridge","request":{"method":"eth_requestAccounts","params":["Curvebot","https://www.curvebot.fi/assets/Favicon.png"]}} provider-bridge.js:1140  content: background > inpage: {"id":"4","jsonrpc":"2.0","result":["0x79c9a765d865f949c18335321436faafa865b2e6"]} 9101-87e71a4c7ee76b91.js:1 args (3) [Array(1), Array(1), Array(1)] 9101-87e71a4c7ee76b91.js:1 Preparing transaction hash... 9101-87e71a4c7ee76b91.js:1 Estimating gas... provider-bridge.js:1135  content: inpage > background: {"id":"5","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}} provider-bridge.js:1140  content: background > inpage: {"id":"5","jsonrpc":"2.0","result":["0x79c9a765d865f949c18335321436faafa865b2e6"]} provider-bridge.js:1135  content: inpage > background: {"id":"6","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}} provider-bridge.js:1140  content: background > inpage: {"id":"6","jsonrpc":"2.0","result":["0x79c9a765d865f949c18335321436faafa865b2e6"]} provider-bridge.js:1135  content: inpage > background: {"id":"7","target":"tally-provider-bridge","request":{"method":"eth_chainId","params":[]}} provider-bridge.js:1140  content: background > inpage: {"id":"7","jsonrpc":"2.0","result":"0x1"} provider-bridge.js:1135  content: inpage > background: {"id":"8","target":"tally-provider-bridge","request":{"method":"eth_estimateGas","params":[{"from":"0x79c9a765d865f949c18335321436faafa865b2e6","to":"0x532d78498bea19051b6b55f53a9ab407a02f41c7","data":"0xc60e14e2000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000e0ec478eaff43593eaee3e6304a4ae15930104a700000000000000000000000000000000000000000000000000000000000000010000000000000000000000009be82cddb5c266e010c97e4b1b5b2df53c16384d0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000e2709cea70791e6d000000000000000000000000000000000000000000000a7e27470f68682bc100"}]}} provider-bridge.js:1140  content: background > inpage: {"id":"8","jsonrpc":"2.0","result":{"code":4001,"message":"Execution reverted: Unauthorized"}} 9101-87e71a4c7ee76b91.js:1 Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="Execution reverted: Unauthorized", method="estimateGas", transaction={"from":"0x79C9A765d865f949c18335321436fAAfa865B2e6","to":"0x532D78498BEA19051B6b55F53A9AB407a02F41C7","data":"0xc60e14e2000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000e0ec478eaff43593eaee3e6304a4ae15930104a700000000000000000000000000000000000000000000000000000000000000010000000000000000000000009be82cddb5c266e010c97e4b1b5b2df53c16384d0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000e2709cea70791e6d000000000000000000000000000000000000000000000a7e27470f68682bc100","accessList":null}, error={"code":4001,"message":"Execution reverted: Unauthorized"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)     at Logger.makeError (_app-6073f09591b54944.js:1:203690)     at Logger.throwError (_app-6073f09591b54944.js:1:203809)     at checkError (_app-6073f09591b54944.js:1:283184)     at Web3Provider.<anonymous> (_app-6073f09591b54944.js:1:293481)     at Generator.throw (<anonymous>)     at rejected (_app-6073f09591b54944.js:1:282225) provider-bridge.js:1140  content: background > inpage: {"id":"tallyHo","jsonrpc":"2.0","result":{"method":"tally_getConfig","defaultWallet":true}} provider-bridge.js:1140  content: background > inpage: {"id":"tallyHo","jsonrpc":"2.0","result":{"method":"tally_getConfig","defaultWallet":true,"chainId":"0x1"}} provider-bridge.js:1135  content: inpage > background: {"id":"9","target":"tally-provider-bridge","request":{"method":"wallet_switchEthereumChain","params":[{"chainId":"0x1"}]}} provider-bridge.js:1140  content: background > inpage: {"id":"9","jsonrpc":"2.0","result":null} provider-bridge.js:1135  content: inpage > background: {"id":"10","target":"tally-provider-bridge","request":{"method":"eth_requestAccounts","params":["Curvebot","https://www.curvebot.fi/assets/Favicon.png"]}} provider-bridge.js:1140  content: background > inpage: {"id":"10","jsonrpc":"2.0","result":["0x79c9a765d865f949c18335321436faafa865b2e6"]} 9101-87e71a4c7ee76b91.js:1 args (3) [Array(1), Array(1), Array(1)] 9101-87e71a4c7ee76b91.js:1 Preparing transaction hash... 9101-87e71a4c7ee76b91.js:1 Estimating gas... provider-bridge.js:1135  content: inpage > background: {"id":"11","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}} provider-bridge.js:1140  content: background > inpage: {"id":"11","jsonrpc":"2.0","result":["0x79c9a765d865f949c18335321436faafa865b2e6"]} provider-bridge.js:1135  content: inpage > background: {"id":"12","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}} provider-bridge.js:1140  content: background > inpage: {"id":"12","jsonrpc":"2.0","result":["0x79c9a765d865f949c18335321436faafa865b2e6"]} provider-bridge.js:1135  content: inpage > background: {"id":"13","target":"tally-provider-bridge","request":{"method":"eth_chainId","params":[]}} provider-bridge.js:1140  content: background > inpage: {"id":"13","jsonrpc":"2.0","result":"0x1"} provider-bridge.js:1135  content: inpage > background: {"id":"14","target":"tally-provider-bridge","request":{"method":"eth_estimateGas","params":[{"from":"0x79c9a765d865f949c18335321436faafa865b2e6","to":"0x532d78498bea19051b6b55f53a9ab407a02f41c7","data":"0xc60e14e2000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000e0ec478eaff43593eaee3e6304a4ae15930104a700000000000000000000000000000000000000000000000000000000000000010000000000000000000000009be82cddb5c266e010c97e4b1b5b2df53c16384d0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000e2709cea70791e6d000000000000000000000000000000000000000000000a7e27470f68682bc100"}]}} provider-bridge.js:1140  content: background > inpage: {"id":"14","jsonrpc":"2.0","result":{"code":4001,"message":"Execution reverted: Unauthorized"}} 9101-87e71a4c7ee76b91.js:1 Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="Execution reverted: Unauthorized", method="estimateGas", transaction={"from":"0x79C9A765d865f949c18335321436fAAfa865B2e6","to":"0x532D78498BEA19051B6b55F53A9AB407a02F41C7","data":"0xc60e14e2000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000e0ec478eaff43593eaee3e6304a4ae15930104a700000000000000000000000000000000000000000000000000000000000000010000000000000000000000009be82cddb5c266e010c97e4b1b5b2df53c16384d0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000e2709cea70791e6d000000000000000000000000000000000000000000000a7e27470f68682bc100","accessList":null}, error={"code":4001,"message":"Execution reverted: Unauthorized"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)     at Logger.makeError (_app-6073f09591b54944.js:1:203690)     at Logger.throwError (_app-6073f09591b54944.js:1:203809)     at checkError (_app-6073f09591b54944.js:1:283184)     at Web3Provider.<anonymous> (_app-6073f09591b54944.js:1:293481)     at Generator.throw (<anonymous>)     at rejected (_app-6073f09591b54944.js:1:282225)
A T
10m
Incoming voice call
Lok Lee
10:24 AM
https://www.coingecko.com/en/coins/mode  I'm fighting to avoid this!
Christian Lohr
Mon
Yeup
Christopher Wall
Mon
Incoming voice call
KP

Kirk Phillips
Mon
ack
Paul Hainsworth
Wed
⁨😭⁩ Sticker message
JA

J.J. Aragonés
Wed
He was so stupid.
Matt Slater
Apr 25
Narp. We rebranded as Squeeze. Juice is gone.
Paloma <> Binary
Apr 25
⁨You⁩: I created a ticket with the full log here: https://github.com/palomachain/paloma/issues/1156  At the block height, we had like 30 validators.  https://paloma.explorers.guru/block/16015222    FY @Anil this is the issue that Vishal reported. If you have any additional data?
Marbar
Apr 23
there are cli commands on the node that should replace it
Şahver Binici
Apr 18
😂
Jack Zampolin
Apr 17
https://coinmarketcap.com/currencies/agoric/

⁨Mason Borda⁩
1 week

Today

from cooley
4:35 PM

should I link this to tokensoft at all?
4:48 PM

Mason Borda
should I link this to tokensoft at all?

Is it narrative? 
5:03 PM

yea I'm worried it gets in the way of narrative
5:03 PM

exactly 
5:03 PM

Today

Botanix Labs raises $8.5 million to build a Bitcoin-native DeFi ecosystem
Following a previously unannounced $3 million pre-seed round last year, the raise brings Botanix Labs’ funding to $11.5 million.
www.theblock.co

https://www.theblock.co/post/292873/botanix-labs-raise-bitcoin-defi
6:56 AM

Narrative
6:56 AM

Nice - I had them on my podcast
7:11 AM

I need a young narrative though
7:11 AM

Mason Borda
I need a young narrative though

Agreed. Ageism is rampant in the industry VC circles.
7:12 AM

But if you are off narrative, you still lose
7:12 AM

Babylon is a bunch of old guys
7:12 AM

Like a good narrative that isn’t played out
7:12 AM

Narrative.
7:12 AM

I don’t mean age
7:12 AM

Mason Borda
Like a good narrative that isn’t played out

Dude. Don't invent narratives. Go with what investors are funding.
7:13 AM

Bitcoin is still getting funded.
7:13 AM

What is SOFT doing for Bitcoin?
7:13 AM

Paloma already has a bridge planned for BitcoinL2
7:17 AM

The New York-based firm said the funds will be used to build the Spiderchain — a Bitcoin-native Layer 2 primitive with full Ethereum Virtual Machine equivalence. More specifically, Botanix Labs will deploy the capital to grow its existing team, focusing on product development.
7:18 AM

LOL
7:18 AM

MG
7:19 AM

OMG
7:19 AM

I had them on my podcast
7:19 AM

A while back
7:19 AM

Like as soon as they made the twitter account
7:19 AM

Narrative 
7:26 AM

soft protocol brings tokenization to Bitcoin L2s
7:52 AM

Mason Borda
soft protocol brings tokenization to Bitcoin L2s

perfect 
8:11 AM

Curvebot
Build algorithmic trading bots on Curve with MEV protection.
www.curvebot.fi

gm ser: Update on the 12ETH. We used the wrong bot to stop and now we have updated. will you please hit https://www.curvebot.fi/mybots/ and let me know if you are able to stop your bot?
11m

1 Unread Message
provider-bridge.js:1140  content: background > inpage: {"id":"tallyHo","jsonrpc":"2.0","result":{"method":"tally_getConfig","defaultWallet":true}}
provider-bridge.js:1140  content: background > inpage: {"id":"tallyHo","jsonrpc":"2.0","result":{"method":"tally_getConfig","defaultWallet":true,"chainId":"0x1"}}
injected.js:1 Uncaught TypeError: Cannot redefine property: ethereum
    at Function.defineProperty (<anonymous>)
    at qVn (injected.js:1:5025960)
    at LVn (injected.js:1:5024975)
    at injected.js:1:5033038
    at injected.js:1:5033045
qVn @ injected.js:1
LVn @ injected.js:1
(anonymous) @ injected.js:1
(anonymous) @ injected.js:1
contentScript.bundle.js:1 Content script works!
contentScript.bundle.js:1 ===> FROM THE PRINT MODULE: Using the 'printLine' function from the Print Module
provider-bridge.js:1135  content: inpage > background: {"id":"0","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}}
provider-bridge.js:1140  content: background > inpage: {"id":"0","jsonrpc":"2.0","result":["0x79c9a765d865f949c18335321436faafa865b2e6"]}
provider-bridge.js:1135  content: inpage > background: {"id":"1","target":"tally-provider-bridge","request":{"method":"net_version","params":[]}}
provider-bridge.js:1140  content: background > inpage: {"id":"1","jsonrpc":"2.0","result":"1"}
provider-bridge.js:1135  content: inpage > background: {"id":"2","target":"tally-provider-bridge","request":{"method":"eth_chainId","params":[]}}
provider-bridge.js:1140  content: background > inpage: {"id":"2","jsonrpc":"2.0","result":"0x1"}
6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: {name: 'MAINNET', chainId: 1}
6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: {name: 'MAINNET', chainId: 1}
6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: {name: 'MAINNET', chainId: 1}
6916-b889c2b489a691b3.js:1 CURVE-JS IS CONNECTED TO NETWORK: {name: 'MAINNET', chainId: 1}
mybots/:1 Third-party cookie will be blocked. Learn more in the Issues tab.
mybots/:1 Third-party cookie will be blocked. Learn more in the Issues tab.
mybots/:1 Third-party cookie will be blocked. Learn more in the Issues tab.
mybots/:1 Third-party cookie will be blocked. Learn more in the Issues tab.
provider-bridge.js:1140  content: background > inpage: {"id":"tallyHo","jsonrpc":"2.0","result":{"method":"tally_getConfig","defaultWallet":true}}
provider-bridge.js:1140  content: background > inpage: {"id":"tallyHo","jsonrpc":"2.0","result":{"method":"tally_getConfig","defaultWallet":true,"chainId":"0x1"}}
provider-bridge.js:1135  content: inpage > background: {"id":"3","target":"tally-provider-bridge","request":{"method":"wallet_switchEthereumChain","params":[{"chainId":"0x1"}]}}
provider-bridge.js:1140  content: background > inpage: {"id":"3","jsonrpc":"2.0","result":null}
provider-bridge.js:1135  content: inpage > background: {"id":"4","target":"tally-provider-bridge","request":{"method":"eth_requestAccounts","params":["Curvebot","https://www.curvebot.fi/assets/Favicon.png"]}}
provider-bridge.js:1140  content: background > inpage: {"id":"4","jsonrpc":"2.0","result":["0x79c9a765d865f949c18335321436faafa865b2e6"]}
9101-87e71a4c7ee76b91.js:1 args (3) [Array(1), Array(1), Array(1)]
9101-87e71a4c7ee76b91.js:1 Preparing transaction hash...
9101-87e71a4c7ee76b91.js:1 Estimating gas...
provider-bridge.js:1135  content: inpage > background: {"id":"5","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}}
provider-bridge.js:1140  content: background > inpage: {"id":"5","jsonrpc":"2.0","result":["0x79c9a765d865f949c18335321436faafa865b2e6"]}
provider-bridge.js:1135  content: inpage > background: {"id":"6","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}}
provider-bridge.js:1140  con... Read more
1m
