### ISSUE TITLE
[BUG] Gravity fails to export to genesis

### ISSUE THREAD

**Issue by maharifu** [VolumeFi/paloma#1654]
When exporting state, the gravity module fails with the error:

```
palomad export --output-document export.json

(...)

panic: last slashed batch block not initialized from genesis

goroutine 199 [running]:
github.com/palomachain/paloma/x/gravity/keeper.ExportGenesis({_, _}, {{0x4722650, 0xc001ef0690}, {0x7ff81bdc05a8, 0xc001afb188}, {0x4726680, 0xc001ef2580}, {0x46c4340, 0xc001145900}, ...})
        /tmp/paloma/x/gravity/keeper/genesis.go:161 +0xf87
github.com/palomachain/paloma/x/gravity.AppModule.ExportGenesis({{{0x4722650, 0xc001ef0690}}, {{0x4722650, 0xc001ef0690}, {0x7ff81bdc05a8, 0xc001afb188}, {0x4726680, 0xc001ef2580}, {0x46c4340, 0xc001145900}, ...}, ...}, ...)
        /tmp/paloma/x/gravity/module.go:164 +0x85
github.com/cosmos/cosmos-sdk/types/module.(*Manager).ExportGenesisForModules.func3({0x7ff81bde5910, 0xc0000318c8}, 0xc0017e6600)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.6/types/module/module.go:584 +0x12d
created by github.com/cosmos/cosmos-sdk/types/module.(*Manager).ExportGenesisForModules in goroutine 1
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.6/types/module/module.go:582 +0x90
```

**Comment by taariq** [comment]
Fixed with https://github.com/palomachain/paloma/commit/3de24c3f238e804ba7a338842c724670cbfa2a7b
