### ISSUE TITLE
[BUG] limit-order-bot-uni-v3-script: not working

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#1670]
I just created a new Uniswap V3 limit order bot but can't see the bot on mybots api result.
https://etherscan.io/tx/0xbc1373d3e64fbb51da445bf1396062212ed049ddb24e6024f2c4366b37bd180e

contract address: 0x3438774d43214Bbf442066b858B3B93F01846C51

**Comment by verabehr** [comment]
```
Jun 10 16:50:25 bots-server start.sh[3372708]: > start
Jun 10 16:50:25 bots-server start.sh[3372708]: > node --openssl-legacy-provider index.js
Jun 10 16:50:26 bots-server start.sh[3372722]: node:events:491
Jun 10 16:50:26 bots-server start.sh[3372722]:       throw er; // Unhandled 'error' event
Jun 10 16:50:26 bots-server start.sh[3372722]:       ^
Jun 10 16:50:26 bots-server start.sh[3372722]: Error: listen EADDRINUSE: address already in use :::3338
Jun 10 16:50:26 bots-server start.sh[3372722]:     at Server.setupListenHandle [as _listen2] (node:net:1740:16)
Jun 10 16:50:26 bots-server start.sh[3372722]:     at listenInCluster (node:net:1788:12)
Jun 10 16:50:26 bots-server start.sh[3372722]:     at Server.listen (node:net:1876:7)
Jun 10 16:50:26 bots-server start.sh[3372722]:     at Function.listen (/home/rootedbox/app/limit-order-bot-uni-v3-script/node_modules/express/lib/application.js:635:24)
Jun 10 16:50:26 bots-server start.sh[3372722]:     at Object.<anonymous> (/home/rootedbox/app/limit-order-bot-uni-v3-script/index.js:18:5)
Jun 10 16:50:26 bots-server start.sh[3372722]:     at Module._compile (node:internal/modules/cjs/loader:1226:14)
Jun 10 16:50:26 bots-server start.sh[3372722]:     at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
Jun 10 16:50:26 bots-server start.sh[3372722]:     at Module.load (node:internal/modules/cjs/loader:1089:32)
Jun 10 16:50:26 bots-server start.sh[3372722]:     at Module._load (node:internal/modules/cjs/loader:930:12)
Jun 10 16:50:26 bots-server start.sh[3372722]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
Jun 10 16:50:26 bots-server start.sh[3372722]: Emitted 'error' event on Server instance at:
Jun 10 16:50:26 bots-server start.sh[3372722]:     at emitErrorNT (node:net:1767:8)
Jun 10 16:50:26 bots-server start.sh[3372722]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
Jun 10 16:50:26 bots-server start.sh[3372722]:   code: 'EADDRINUSE',
Jun 10 16:50:26 bots-server start.sh[3372722]:   errno: -98,
Jun 10 16:50:26 bots-server start.sh[3372722]:   syscall: 'listen',
Jun 10 16:50:26 bots-server start.sh[3372722]:   address: '::',
Jun 10 16:50:26 bots-server start.sh[3372722]:   port: 3338
Jun 10 16:50:26 bots-server start.sh[3372722]: }
```

**Comment by ranshaojiqing** [comment]
after looking into this, the data is missing from the db. likely deeper issues at play here than just the mybots api.

investigating the backend code.

**Comment by verabehr** [comment]
There seem to be two issues: 
1. We're using a port that is not free. Still trying to figure out how to use one that is actually free
2. There are some smaller issues in the script - see linked PR

**Comment by verabehr** [comment]
3. The ABI was outdated in the networks.json

**Comment by verabehr** [comment]
@webelf101 will you take a look at this? The script with the latest code from github produces no errors, but it also doesn't pull in the one bot that was created on the contract. https://etherscan.io/address/0x3438774d43214Bbf442066b858B3B93F01846C51

I then manually set the `fromBlock` directly in the server limit-orders.js (line 227) file to 20042107 and then get a SQL not unique constraint error from the script. 

```
Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: deposits.deposit_id
Jun 18 14:37:06 bots-server start.sh[2342308]: --> in Statement#run([
Jun 18 14:37:06 bots-server start.sh[2342308]:   0n,
Jun 18 14:37:06 bots-server start.sh[2342308]:   '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE',
Jun 18 14:37:06 bots-server start.sh[2342308]:   '0xD533a949740bb3306d119CC777fa900bA034cd52',
Jun 18 14:37:06 bots-server start.sh[2342308]:   3000000000000000n,
Jun 18 14:37:06 bots-server start.sh[2342308]:   '0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432',
Jun 18 14:37:06 bots-server start.sh[2342308]:   0,
Jun 18 14:37:06 bots-server start.sh[2342308]:   0.303398,
Jun 18 14:37:06 bots-server start.sh[2342308]:   0,
Jun 18 14:37:06 bots-server start.sh[2342308]:   0.303398,
Jun 18 14:37:06 bots-server start.sh[2342308]:   169,
Jun 18 14:37:06 bots-server start.sh[2342308]:   1717875617n,
Jun 18 14:37:06 bots-server start.sh[2342308]:   'ETH',
Jun 18 14:37:06 bots-server start.sh[2342308]:   'uniswapv3',
Jun 18 14:37:06 bots-server start.sh[2342308]:   'limitOrder',
Jun 18 14:37:06 bots-server start.sh[2342308]:   '0x3438774d43214Bbf442066b858B3B93F01846C51',
Jun 18 14:37:06 bots-server start.sh[2342308]:   false
Jun 18 14:37:06 bots-server start.sh[2342308]: ], [Function (anonymous)])
```
