### ISSUE TITLE
[BUG] curve healthy bot repay creates an error

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1678]
There are two error messages recorded in the lgos when the backend tries to repay bot 0xD694e9c66C353a72df4B6C03C24B997027cE2d26 due to low health 

```
Jun 10 16:17:11 bots-server start.sh[2932999]: executeithdraw bot_info [
Jun 10 16:17:11 bots-server start.sh[2932999]:   {
Jun 10 16:17:11 bots-server start.sh[2932999]:     bot: '0xD694e9c66C353a72df4B6C03C24B997027cE2d26',
Jun 10 16:17:11 bots-server start.sh[2932999]:     callbacker: '0xb911D7e59BA82FDF477a2Ab22Ff25125072C9282',
Jun 10 16:17:11 bots-server start.sh[2932999]:     callback_args: [ '1', '5020', '352426873' ]
Jun 10 16:17:11 bots-server start.sh[2932999]:   }
Jun 10 16:17:11 bots-server start.sh[2932999]: ]
Jun 10 16:17:11 bots-server start.sh[2932999]: EXECUTEITHDRAW Error: Request failed with status code 500
Jun 10 16:17:11 bots-server start.sh[2932999]:     at createError (/home/rootedbox/app/curve-healthy-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/core/createError.js:16:15)
Jun 10 16:17:11 bots-server start.sh[2932999]:     at settle (/home/rootedbox/app/curve-healthy-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/core/settle.js:17:12)
Jun 10 16:17:11 bots-server start.sh[2932999]:     at IncomingMessage.handleStreamEnd (/home/rootedbox/app/curve-healthy-bot/node_modules/@palomachain/paloma.js/node_modules/axios/lib/adapters/http.js:322:11)
Jun 10 16:17:11 bots-server start.sh[2932999]:     at IncomingMessage.emit (node:events:525:35)
Jun 10 16:17:11 bots-server start.sh[2932999]:     at IncomingMessage.emit (node:domain:489:12)
Jun 10 16:17:11 bots-server start.sh[2932999]:     at endReadableNT (node:internal/streams/readable:1359:12)
Jun 10 16:17:11 bots-server start.sh[2932999]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
```

```
Jun 10 16:17:11 bots-server start.sh[2932999]:     data: {
Jun 10 16:17:11 bots-server start.sh[2932999]:       code: 2,
Jun 10 16:17:11 bots-server start.sh[2932999]:       message: "failed to execute message; message index: 0: Error parsing into type curve_healthy_juice_bot_cw::msg::ExecuteMsg: missing field `swap_infos`: execute wasm contract failed [!cosm!wasm/wasmd@v0.50.0/x/wasm/keeper/keeper.go:404] with gas used: '97003'",
Jun 10 16:17:11 bots-server start.sh[2932999]:       details: []
Jun 10 16:17:11 bots-server start.sh[2932999]:     }
```

**Comment by verabehr** [comment]
wc117 — Today at 2:56 PM
I found backend service needs to get swap route to exchange the token to settlement token on Curve and put it as swap_route params. Because we are missing the parameter, the backend script returns an error.

**Comment by verabehr** [comment]
same as https://github.com/VolumeFi/paloma/issues/1679 - closing
