### ISSUE TITLE
BUG: llamelend: unable to start bot`SyntaxError: Cannot convert Infinity to a BigInt`

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1713]
llamalend WSTETH SQUEEZE BOT: Cannot convert Infinity to a BigInt

![Image](https://github.com/VolumeFi/paloma/assets/19958639/cbb39cd2-ce9c-430c-b513-0bf6de52890e)

```
SyntaxError: Cannot convert Infinity to a BigInt (at _app-bf4384c0b5375200.js:6956:39518)
    at BigInt (<anonymous>)
    at numberToHex (_app-bf4384c0b5375200.js:6956:39518)
    at signed (_app-bf4384c0b5375200.js:6956:25981)
    at prepareParam (_app-bf4384c0b5375200.js:6956:26005)
    at J.params (_app-bf4384c0b5375200.js:6956:26770)
    at encodeAbiParameters (_app-bf4384c0b5375200.js:6956:26808)
    at encodeFunctionData (_app-bf4384c0b5375200.js:6956:28276)
    at readContract (_app-bf4384c0b5375200.js:1323:108850)
    at Object.readContract (_app-bf4384c0b5375200.js:1324:7043)
    at chunk_TSH6VVF4_readContract (_app-bf4384c0b5375200.js:1327:15255)
numberToHex @ _app-bf4384c0b5375200.js:6956
signed @ _app-bf4384c0b5375200.js:6956
prepareParam @ _app-bf4384c0b5375200.js:6956
J.params @ _app-bf4384c0b5375200.js:6956
encodeAbiParameters @ _app-bf4384c0b5375200.js:6956
encodeFunctionData @ _app-bf4384c0b5375200.js:6956
readContract @ _app-bf4384c0b5375200.js:1323
readContract @ _app-bf4384c0b5375200.js:1324
chunk_TSH6VVF4_readContract @ _app-bf4384c0b5375200.js:1327
getCallbackArgs @ [id]-052863a86a1af11a.js:1
setTimeout (async)
(anonymous) @ [id]-052863a86a1af11a.js:1
Rj @ framework-ca706bf673a13738.js:9
Ik @ framework-ca706bf673a13738.js:9
(anonymous) @ framework-ca706bf673a13738.js:9
Qk @ framework-ca706bf673a13738.js:9
Fk @ framework-ca706bf673a13738.js:9
jg @ framework-ca706bf673a13738.js:9
Sk @ framework-ca706bf673a13738.js:9
Jb @ framework-ca706bf673a13738.js:9
hd @ framework-ca706bf673a13738.js:9
fd @ framework-ca706bf673a13738.js:9
ed @ framework-ca706bf673a13738.js:9
```

**Comment by verabehr** [comment]
This is happening because there is an error with the backend api https://one.palomachain.com/quote?dst=0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0&src=0xf939e0a03fb07f59a73314e73794be0e57ac1b4e&amount=1000000000000000000&chain=1

**Comment by verabehr** [comment]
service wasn't running - restarted and that solved the issue
