### ISSUE TITLE
BUG: llamalend - reducing default squeeze level results in `ContractFunctionExecutionError`

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1714]
Steps: 

1. go to llamalend susde bot
2. Enter deposit token and amount
3. reduce squeeze level on slider

expected: I should be able to start a bot without error with the selected squeeze level
actual: I'm getting the following error: 
```
ContractFunctionExecutionError
    at getContractError (_app-bf4384c0b5375200.js:1323:108656)
    at readContract (_app-bf4384c0b5375200.js:1323:109028)
    at async getHealth ([id]-052863a86a1af11a.js:1:19045)
    at async [id]-052863a86a1af11a.js:1:26500Caused by: ContractFunctionRevertedError
    at getContractError (_app-bf4384c0b5375200.js:1323:108561)
    at readContract (_app-bf4384c0b5375200.js:1323:109028)
    at async getHealth ([id]-052863a86a1af11a.js:1:19045)
    at async [id]-052863a86a1af11a.js:1:26500
```

![Image](https://github.com/VolumeFi/paloma/assets/19958639/aa21110a-2bcc-4025-ad12-89d889333977)

**Comment by verabehr** [comment]
confirmed this is working now
