### ISSUE TITLE
[BUG] Uniswap v3 contract execution failure

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1765]
```
Jun 21 19:48:44 bots-server start.sh[2492084]:     },
Jun 21 19:48:44 bots-server start.sh[2492084]:     data: {
Jun 21 19:48:44 bots-server start.sh[2492084]:       code: 2,
Jun 21 19:48:44 bots-server start.sh[2492084]:       message: "failed to execute message; message index: 0: AllPending: execute wasm contract failed [!cosm!wasm/wasmd@v0.50.0/x/wasm/keeper/keeper.go:404] with gas used: '98952'",
Jun 21 19:48:44 bots-server start.sh[2492084]:       details: []
Jun 21 19:48:44 bots-server start.sh[2492084]:     }
Jun 21 19:48:44 bots-server start.sh[2492084]:   },
Jun 21 19:48:44 bots-server start.sh[2492084]:   isAxiosError: true,
Jun 21 19:48:44 bots-server start.sh[2492084]:   toJSON: [Function: toJSON]
Jun 21 19:48:44 bots-server start.sh[2492084]: }
Jun 21 19:48:52 bots-server start.sh[2492084]: getMinAmount exception: ContractExecutionError: Error happened while trying to execute a function inside a smart contract
Jun 21 19:48:52 bots-server start.sh[2492084]:     at Web3RequestManager._isReverted (/home/rootedbox/app/limit-order-bot-uni-v3-script/node_modules/web3-core/lib/commonjs/web3_request_manager.js:311:19)
Jun 21 19:48:52 bots-server start.sh[2492084]:     at Web3RequestManager._processJsonRpcResponse (/home/rootedbox/app/limit-order-bot-uni-v3-script/node_modules/web3-core/lib/commonjs/web3_request_manager.js:257:42)
Jun 21 19:48:52 bots-server start.sh[2492084]:     at Web3RequestManager.<anonymous> (/home/rootedbox/app/limit-order-bot-uni-v3-script/node_modules/web3-core/lib/commonjs/web3_request_manager.js:156:29)
Jun 21 19:48:52 bots-server start.sh[2492084]:     at Generator.next (<anonymous>)
Jun 21 19:48:52 bots-server start.sh[2492084]:     at fulfilled (/home/rootedbox/app/limit-order-bot-uni-v3-script/node_modules/web3-core/lib/commonjs/web3_request_manager.js:21:58)
Jun 21 19:48:52 bots-server start.sh[2492084]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
Jun 21 19:48:52 bots-server start.sh[2492084]:   innerError: [Eip838ExecutionError: execution reverted] {
Jun 21 19:48:52 bots-server start.sh[2492084]:     innerError: undefined,
Jun 21 19:48:52 bots-server start.sh[2492084]:     code: -32000,
Jun 21 19:48:52 bots-server start.sh[2492084]:     receipt: undefined,
Jun 21 19:48:52 bots-server start.sh[2492084]:     data: undefined
Jun 21 19:48:52 bots-server start.sh[2492084]:   },
Jun 21 19:48:52 bots-server start.sh[2492084]:   code: 310,
Jun 21 19:48:52 bots-server start.sh[2492084]:   receipt: undefined11
Jun 21 19:48:52 bots-server start.sh[2492084]: }
Jun 21 19:48:52 bots-server start.sh[2492084]: Error: Request failed with status code 5001```

**Comment by taariq** [comment]
Closing as won't ship.
