### ISSUE TITLE
[BUG] Unable to start CRV ETH Llamalend Bot: Error: cannot estimate gas; transaction may fail or may require manual gas limit 

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1812]
Bot: 

![Image](https://github.com/VolumeFi/paloma/assets/701864/29df69ed-f9d4-40e5-a943-bbacc9de1148)

Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: Debt too high", method="estimateGas", transaction={"from":"0x83334ef0C6f6396413C508A7762741e9FD8B20E9","to":"0xDA426Ef568e3e1cA7EFcf169D7b293cCB0be62e7","value":{"type":"BigNumber","hex":"0x01aa535d3d0c0000"},"data":"0x93dbfd1f00000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000d533a949740bb3306d119cc777fa900ba034cd5200000000000000000000000000000000000000000000003d1a27b03440c10e4a0000000000000000000000000000000000000000000000000000000000000004000000000000000000000000e61d72cb6d30bc21a623875f160682e6c17b005e000000000000000000000000000000000000000000000000000000000000076000000000000000000000000000000000000000000000000000000000000007e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000028a00000000000000000000000000000000000000000000000000000000000009c400000000000000000000000000000000000000000000000000000000000000c800000000000000000000000000000000000000000000000000000007be3567880000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000004ebdf703948ddcea3b11f675b4d1fba9d2414a14000000000000000000000000d533a949740bb3306d119cc777fa900ba034cd5200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d529ae9e860000000000000000000000000000000000000000000000000027e545ba58c58cb5db00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003e807ed2379000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd09000000000000000000000000f939e0a03fb07f59a73314e73794be0e57ac1b4e000000000000000000000000d533a949740bb3306d119cc777fa900ba034cd52000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd09000000000000000000000000e61d72cb6d30bc21a623875f160682e6c17b005e00000000000000000000000000000000000000000000003d1a27b03440c10e4a0000000000000000000000000000000000000000000000d8bb611703b961264800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000029300000000000000000000000000000000000000000000000000027500024700a007e5c0d20000000000000000000000000000000000000000000002230001c00000d05122e0438eb3703bf871e31ce639bd351109c88666eaf939e0a03fb07f59a73314e73794be0e57ac1b4e0044a64833a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd09513202704ed8b5a8e817f354d59432e115e0d80533942260fac5e5542a773aa44fbcfedf7c193bc2c599004475d39ecb000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd090000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000276a400000000000000000000000000000000000000000000000004881f9cbd08041900000000000000000000000000000000000000000000000000000000668ad2f602a00000000000000000000000000000000000000000000000d8bb611703b9612648ee63c1e581919fa96e88d67499339577fa202345436bcdaf79c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2111111125421ca6dc452d289314280a0f8842a650020d6bdbf78d533a949740bb3306d119cc777fa900ba034cd52111111125421ca6dc452d289314280a0f8842a65000000000000000000000000009ea1eb89000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"execution reverted: Debt too high","data":{"originalError":{"message":"execution reverted: Debt too high","code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000d4465627420746f6f206869676800000000000000000000000000000000000000"}}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (_app-f4ad74323858b852.js:1:204760)
    at Logger.throwError (_app-f4ad74323858b852.js:1:204879)
    at checkError (_app-f4ad74323858b852.js:1:284279)
    at Web3Provider.<anonymous> (_app-f4ad74323858b852.js:1:294576)
    at Generator.throw (<anonymous>)
    at rejected (_app-f4ad74323858b852.js:1:283320)

**Comment by taariq** [comment]
Closing as won't ship.
