### ISSUE TITLE
[DEVOPS - BUG] FCD not working correctly

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#1883]
There are currently 2 issues 

1. fcd_collector service exits with 
```07-17 18:04 [ERROR]: getaddrinfo EAI_AGAIN lcd.palomachain.com
Jul 17 18:04:57 lcd-mainnet bash[1062284]: Error: getaddrinfo EAI_AGAIN lcd.palomachain.com
Jul 17 18:04:57 lcd-mainnet bash[1062284]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
```
and 
```
07-17 18:05 [ERROR]: Connect Timeout Error
Jul 17 18:05:34 lcd-mainnet bash[1063828]: ConnectTimeoutError: Connect Timeout Error
Jul 17 18:05:34 lcd-mainnet bash[1063828]:     at onConnectTimeout (/home/fcd/fcd/node_modules/undici/lib/core/connect.js:182:24)
Jul 17 18:05:34 lcd-mainnet bash[1063828]:     at /home/fcd/fcd/node_modules/undici/lib/core/connect.js:129:46
Jul 17 18:05:34 lcd-mainnet bash[1063828]:     at Immediate._onImmediate (/home/fcd/fcd/node_modules/undici/lib/core/connect.js:170:9)
Jul 17 18:05:34 lcd-mainnet bash[1063828]:     at processImmediate (node:internal/timers:466:21)
```

2. lcd_api service exits with 
```
]: 07-17 18:07 [INFO]: Paloma FCD Suite is listening on port 3060
Jul 17 18:07:35 lcd-mainnet bash[1069654]: 07-17 18:07 [INFO]: RPCWatcher: connection lost
Jul 17 18:07:35 lcd-mainnet bash[1069654]: 07-17 18:07 [ERROR]: RPCWatcher: error: TIMEOUT
Jul 17 18:07:35 lcd-mainnet bash[1069654]: /home/fcd/fcd/node_modules/ws/lib/websocket.js:285
Jul 17 18:07:35 lcd-mainnet bash[1069654]:       abortHandshake(this, this._req, msg);
Jul 17 18:07:35 lcd-mainnet bash[1069654]:       ^
Jul 17 18:07:35 lcd-mainnet bash[1069654]: Error: WebSocket was closed before the connection was established
Jul 17 18:07:35 lcd-mainnet bash[1069654]:     at WebSocket.close (/home/fcd/fcd/node_modules/ws/lib/websocket.js:285:7)
Jul 17 18:07:35 lcd-mainnet bash[1069654]:     at ReconnectingWebSocket._disconnect (/home/fcd/fcd/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:539:22)
Jul 17 18:07:35 lcd-mainnet bash[1069654]:     at ReconnectingWebSocket._handleError (/home/fcd/fcd/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:180:19)
Jul 17 18:07:35 lcd-mainnet bash[1069654]:     at ReconnectingWebSocket._handleTimeout (/home/fcd/fcd/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:529:14)
Jul 17 18:07:35 lcd-mainnet bash[1069654]:     at Timeout.<anonymous> (/home/fcd/fcd/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:524:75)
Jul 17 18:07:35 lcd-mainnet bash[1069654]:     at listOnTimeout (node:internal/timers:559:17)
Jul 17 18:07:35 lcd-mainnet bash[1069654]:     at processTimers (node:internal/timers:502:7)
```

already done  during trouble shooting in `/home/fcd/fcd/run_collector.sh` and `/home/fcd/fcd/run_api.sh`
1. updated endpoints from lcd2 and rpc2 to lcd and rpc since lcd2 and rpc2 are not yet set up in namecheap
2. updated chain id to `tumbler`
3. updated initial_height to first block on tumbler (15841320)

**Comment by taariq** [comment]
Closing for now.
