### ISSUE TITLE
[LIGHTNODE SALE BUG] Can't buy node due to gas estimation error

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#2004]
purchase/:28 null
_app-f24ac65b86a7a155.js:359 No API key. Please provide a clientId. It is required to access thirdweb's services. You can create a key at https://thirdweb.com/create-api-key
checkClientIdOrSecretKey @ _app-f24ac65b86a7a155.js:359
purchase-a1a018cfa83511de.js:1 date 1723817211176
pulse.walletconnect.com/e:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
contentScript.bundle.js:1 Content script works!
contentScript.bundle.js:1 ===> FROM THE PRINT MODULE: Using the 'printLine' function from the Print Module
purchase/:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: chrome-extension://liecbddmkiiihnedobmlmillhodjkdmb/fonts/CircularXXWeb-Book.woff2
_app-f24ac65b86a7a155.js:467 Object Object Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
    at JsonRpcProvider.onClose (5021.1886ae8f88cf8855.js:1:2291)
    at EventEmitter.<anonymous> (5021.1886ae8f88cf8855.js:1:2928)
    at EventEmitter.emit (_app-f24ac65b86a7a155.js:393:231257)
    at f.onClose (_app-f24ac65b86a7a155.js:383:20576)
    at x.onclose (_app-f24ac65b86a7a155.js:383:20444)
X.<computed> @ _app-f24ac65b86a7a155.js:467
_app-f24ac65b86a7a155.js:467 Object Object Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
    at JsonRpcProvider.onClose (5021.1886ae8f88cf8855.js:1:2291)
    at EventEmitter.<anonymous> (5021.1886ae8f88cf8855.js:1:2928)
    at EventEmitter.emit (_app-f24ac65b86a7a155.js:393:231257)
    at f.onClose (_app-f24ac65b86a7a155.js:383:20576)
    at x.onclose (_app-f24ac65b86a7a155.js:383:20444)
X.<computed> @ _app-f24ac65b86a7a155.js:467
_app-f24ac65b86a7a155.js:467 Object Object Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
    at JsonRpcProvider.onClose (5021.1886ae8f88cf8855.js:1:2291)
    at EventEmitter.<anonymous> (5021.1886ae8f88cf8855.js:1:2928)
    at EventEmitter.emit (_app-f24ac65b86a7a155.js:393:231257)
    at f.onClose (_app-f24ac65b86a7a155.js:383:20576)
    at x.onclose (_app-f24ac65b86a7a155.js:383:20444)
X.<computed> @ _app-f24ac65b86a7a155.js:467
purchase-a1a018cfa83511de.js:1 date 1723817253138
_app-f24ac65b86a7a155.js:467 Object Object Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
    at JsonRpcProvider.onClose (5021.1886ae8f88cf8855.js:1:2291)
    at EventEmitter.<anonymous> (5021.1886ae8f88cf8855.js:1:2928)
    at EventEmitter.emit (_app-f24ac65b86a7a155.js:393:231257)
    at f.onClose (_app-f24ac65b86a7a155.js:383:20576)
    at x.onclose (_app-f24ac65b86a7a155.js:383:20444)
X.<computed> @ _app-f24ac65b86a7a155.js:467
assets/images/Try_again.svg:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
1172-6c865e2c0ad0ca17.js:1 SyntaxError: Cannot convert Infinity to a BigInt
    at o.BigInt (8157-d8061ed22dcfa03b.js:4:368136)
    at CurrencyAmount.Fraction (8157-d8061ed22dcfa03b.js:1:37178)
    at new CurrencyAmount (8157-d8061ed22dcfa03b.js:1:40011)
    at CurrencyAmount.fromRawAmount (8157-d8061ed22dcfa03b.js:1:40249)
    at generateRoute (1172-6c865e2c0ad0ca17.js:1:30597)
    at getSwapPath (1172-6c865e2c0ad0ca17.js:1:31112)
    at changeAmount (1172-6c865e2c0ad0ca17.js:1:41773)
    at 1172-6c865e2c0ad0ca17.js:1:41860
    at Qj (framework-fee8a7e75612eda8.js:9:84134)
    at Hk (framework-fee8a7e75612eda8.js:9:113133)
1172-6c865e2c0ad0ca17.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at getSwapPathForV3 (1172-6c865e2c0ad0ca17.js:1:33801)
    at changeAmount (1172-6c865e2c0ad0ca17.js:1:41829)
getSwapPathForV3 @ 1172-6c865e2c0ad0ca17.js:1
purchase/:1 Access to XMLHttpRequest at 'https://cloudflare-ipfs.com/ipns/api.uniswap.org/v1/pools/v3/mainnet.json' from origin 'https://www.palomachain.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
cloudflare-ipfs.com/ipns/api.uniswap.org/v1/pools/v3/mainnet.json:1 
        
        
       Failed to load resource: net::ERR_FAILED
5035-f94d19af5a1e1f02.js:1 args Array(6)
inpage.js:1 MetaMask - RPC Error: execution reverted: STF Object
(anonymous) @ inpage.js:1
_app-f24ac65b86a7a155.js:426 e Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: STF", method="estimateGas", transaction={"from":"0x48ef7beE7c93986256c9Db4B34d353fB0c00CB32","to":"0x71Ed10958cd5aE119F0E668fc1840e87507859c6","value":{"type":"BigNumber","hex":"0x916b299ec93d50"},"data":"0xad310f1d00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000005f5e100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002ba0b86991c6218b36c1d19d4a2e9eb0ce3606eb48000064c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"execution reverted: STF","data":{"originalError":{"code":3,"data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000035354460000000000000000000000000000000000000000000000000000000000","message":"execution reverted: STF"}}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (_app-f24ac65b86a7a155.js:1:477297)
    at Logger.throwError (_app-f24ac65b86a7a155.js:1:477419)
    at checkError (_app-f24ac65b86a7a155.js:1:557753)
    at Web3Provider.<anonymous> (_app-f24ac65b86a7a155.js:1:568114)
    at Generator.throw (<anonymous>)
    at rejected (_app-f24ac65b86a7a155.js:1:556773)

**Comment by verabehr** [comment]
@jamie088 false alarm, it did not actually work. Here is the error from etherscan after joyce confirmed the transaction in metamask https://etherscan.io/tx/0x2e17c561a46b34a77a47397117536709a3b309e8fc2e68016cf052dbb0f74405

**Comment by taariq** [comment]
fixed with https://github.com/palomachain/website/pull/114
