### ISSUE TITLE
[LIGHTNODE SALE] BUG Failed to load resource: the server responded with a status of 403 () when connecting metamask

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2016]
When connecting metamask to validate node, I get the error:

       **Failed to load resource: the server responded with a status of 403 ()**
_app-040909541247f7bc.js:467 Object Object Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
    at JsonRpcProvider.onClose (5021.1886ae8f88cf8855.js:1:2291)
    at EventEmitter.<anonymous> (5021.1886ae8f88cf8855.js:1:2928)
    at EventEmitter.emit (_app-040909541247f7bc.js:393:231257)
    at f.onClose (_app-040909541247f7bc.js:383:20576)
    at x.onclose (_app-040909541247f7bc.js:383:20444)
X.<computed> @ _app-040909541247f7bc.js:467

_app-040909541247f7bc.js:467 Object Object Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
    at JsonRpcProvider.onClose (5021.1886ae8f88cf8855.js:1:2291)
    at EventEmitter.<anonymous> (5021.1886ae8f88cf8855.js:1:2928)
    at EventEmitter.emit (_app-040909541247f7bc.js:393:231257)
    at f.onClose (_app-040909541247f7bc.js:383:20576)
    at x.onclose (_app-040909541247f7bc.js:383:20444)
X.<computed> @ _app-040909541247f7bc.js:467

**Comment by taariq** [comment]
Closing as shipped. We will debug and bug tickets in prod.
