### ISSUE TITLE
[LIGHTNODE SALE] BUG TypeError: Cannot read properties of null (reading 'toHexString')

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2027]
After token approval of USDC to purchase lightnode, user gets the error and is unable to proceed in the sale.

_app-307eb5f5626dadb9.js:426 e TypeError: Cannot read properties of null (reading 'toHexString')
    at isHexable (_app-307eb5f5626dadb9.js:1:357691)
    at arrayify (_app-307eb5f5626dadb9.js:1:358546)
    at BytesCoder.encode (_app-307eb5f5626dadb9.js:1:299108)
    at _app-307eb5f5626dadb9.js:1:296792
    at Array.forEach (<anonymous>)
    at pack (_app-307eb5f5626dadb9.js:1:296731)
    at TupleCoder.encode (_app-307eb5f5626dadb9.js:1:301564)
    at AbiCoder.encode (_app-307eb5f5626dadb9.js:1:303227)
    at Interface._encodeParams (_app-307eb5f5626dadb9.js:1:326346)
    at Interface.encodeFunctionData (_app-307eb5f5626dadb9.js:1:327292)

**Comment by jamie088** [comment]
@taariq @joycehermosilla Due to a Vyper contract issue, **USDC** token cannot be used as a Purchasing Token now. Need to fix the contract. I will create a new ticket and assign it to Jacky.

**Comment by taariq** [comment]
> @taariq @joycehermosilla Due to a Vyper contract issue, **USDC** token cannot be used as a Purchasing Token now. Need to fix the contract. I will create a new ticket and assign it to Jacky.
> 
>     * If you want test before fixing the contract, please don't use the USDC.

FYI @fullstack412

**Comment by taariq** [comment]
Superseded by https://github.com/VolumeFi/paloma/issues/2029
