### ISSUE TITLE
[BUG] Error: Coin with address '0x5c147e74d63b1d31aa3fd78eb229b65161983b2b' is not available

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2084]
When trying to curve TWAP WrappedFlow that was added to the token lists today.

{"id":"wrapped-flow","symbol":"wflow","name":"Wrapped Flow","platforms":{"ethereum":"0x5c147e74d63b1d31aa3fd78eb229b65161983b2b"}}

**Error**
7203-121b3d46652b7c01.js:1 Error: unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.7.2)
    at Logger.makeError (_app-3cac5a433058b013.js:1:207634)
    at Logger.throwError (_app-3cac5a433058b013.js:1:207758)
    at _app-3cac5a433058b013.js:1:291573
    at async Promise.all (curve-twap/index 1)
7203-121b3d46652b7c01.js:1 Error: unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.7.2)
    at Logger.makeError (_app-3cac5a433058b013.js:1:207634)
    at Logger.throwError (_app-3cac5a433058b013.js:1:207758)
    at _app-3cac5a433058b013.js:1:291573
    at async Promise.all (curve-twap/index 1)
7203-121b3d46652b7c01.js:1 e Error: Coin with address '0x5c147e74d63b1d31aa3fd78eb229b65161983b2b' is not available
    at _getCoinAddresses (5353-d6039e1c572133f0.js:1:2273513)
    at 5353-d6039e1c572133f0.js:1:2061686
    at 5353-d6039e1c572133f0.js:1:2044512
    at Object.next (5353-d6039e1c572133f0.js:1:2044617)
    at 5353-d6039e1c572133f0.js:1:2043510
    at new Promise (<anonymous>)
    at router_awaiter (5353-d6039e1c572133f0.js:1:2043217)
    at Object.getBestRouteAndOutput (5353-d6039e1c572133f0.js:1:2061535)
    at 7203-121b3d46652b7c01.js:1:6261
    at Array.map (<anonymous>)

**Comment by taariq** [comment]
Closing ticket. Need to remove from Curve.
