### ISSUE TITLE
[LIGHTNODE] Review of the Credit Card Purchase Flow.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2153]
1. Remove Connect Wallet Action on the purchase page
2. Add Bank Account as option. Move Credit Card & Bank Account to the top
3. On Selection Purchase LightNode
4. Select Payment Method
5. If Credit Card or Bank Account Selectd, Remove "Select Token"
6. Change "Log In" to "Buy Now
7. Email input verfication do not block alias
8. After registration, no need to login.
9. Login gives error: 
login-93a3084f7e574b30.js:1 TypeError: Cannot read properties of null (reading 'includes')
    at onClickLogin (login-93a3084f7e574b30.js:1:2209)
    at Object.Nb (framework-fee8a7e75612eda8.js:9:14968)
    at Tb (framework-fee8a7e75612eda8.js:9:15122)
    at framework-fee8a7e75612eda8.js:9:33458
    at nf (framework-fee8a7e75612eda8.js:9:33557)
    at se (framework-fee8a7e75612eda8.js:9:33971)
    at framework-fee8a7e75612eda8.js:9:39426
    at Qk (framework-fee8a7e75612eda8.js:9:96323)
    at Jb (framework-fee8a7e75612eda8.js:9:14106)
    at hd (framework-fee8a7e75612eda8.js:9:35261)
﻿

**Comment by taariq** [comment]
Closed as fixed.
