### ISSUE TITLE
[BUG] Unable to make purchase - Error: Extension context invalidated. when using Metamask to purchase

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2225]
Unable to make purchase with Metamask.

Error: Extension context invalidated.
(anonymous) @ chrome-extension://n…ckdown-install.js:1
 Error: Extension context invalidated.
(anonymous) @ chrome-extension://n…ckdown-install.js:1
5chrome-extension://d…hfoodbb/inject.js:1 Uncaught Error: Extension context invalidated.
    at p.postMessage (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/inject.js:1:14136)
    at d.forwardMessage (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/inject.js:1:13639)
    at forwardMessageTo2 (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/inject.js:1:13472)
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/inject.js:1:13065
    at Set.forEach (<anonymous>)
    at handleMessage (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/inject.js:1:12992)

![Image](https://github.com/user-attachments/assets/5a3b3a21-2fca-44d6-ac0b-b7939dd57ac2)

**Comment by jamie088** [comment]
@taariq I guess you have Metamask and Frame installed in one browser, right?

**Comment by taariq** [comment]
> [@taariq](https://github.com/taariq) I guess you have Metamask and Frame installed in one browser, right?

I don't know if they had Frame. Sorry for the late response.

**Comment by taariq** [comment]
Closing. user was able to amke purchase.
