### ISSUE TITLE
[BUG] User attempting to purchase LightNode with Coinbase Wallet on ethereum Failed to load resource: the server responded with a status of 400 ()

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2320]
User attempting to purchase gets error:
Failed to load resource: the server responded with a status of 400 (Bad Request)
[www.palomachain.com-1729806342554.log](https://github.com/user-attachments/files/17513546/www.palomachain.com-1729806342554.log)

        
        
       Failed to load resource: the server responded with a status of 400 ()
_app-918d9b6db0173711.js:374 e Error: bad response (status=400, headers={"content-length":"98","content-type":"application/json"}, body="{\"jsonrpc\":\"2.0\",\"id\":45,\"error\":{\"code\":-32604,\"message\":\"this request method is not supported\"}}", requestBody="{\"method\":\"eth_requestAccounts\",\"params\":[],\"id\":45,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://serene-divine-crater.quiknode.pro/", code=SERVER_ERROR, version=web/5.7.1)
    at h.makeError (_app-918d9b6db0173711.js:1:456147)
    at h.throwError (_app-918d9b6db0173711.js:1:456261)
    at a (_app-918d9b6db0173711.js:1:617876)
    at a.next (<anonymous>)
    at o (_app-918d9b6db0173711.js:1:618710)
nodesale.palomachain.com/api/v1/addaddr:1 
      

![Image](https://github.com/user-attachments/assets/b13baae7-4aa6-490a-9b6d-7bc1c10ce7a6)

**Comment by taariq** [comment]
Unable to repro.  Works with Coinbase wallet.
