### ISSUE TITLE
[BUG] Failed to load resource: the server responded with a status of 400 (Bad Request) nodesale.palomachain.com/api/v2/login:1

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2332]
Unable to Login:

       Failed to load resource: the server responded with a status of 400 (Bad Request)
nodesale.palomachain.com/api/v2/login:1 
        
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)
nodesale.palomachain.com/api/v2/login:1 
        
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)
nodesale.palomachain.com/api/v2/login:1 
        
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)
_app-9be4d72179659790.js:374 Object Object Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
    at x.onClose (5021.2a7451026a1ac452.js:1:2174)
    at a.<anonymous> (5021.2a7451026a1ac452.js:1:2811)
    at a.emit (_app-9be4d72179659790.js:374:362371)
    at l.onClose (_app-9be4d72179659790.js:374:25999)
    at e.onclose (_app-9be4d72179659790.js:374:25867)
t.<computed> @ _app-9be4d72179659790.js:374
nodesale.palomachain.com/api/v2/login:1 
        
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)
nodesale.palomachain.com/api/v2/login:1 
        
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)
nodesale.palomachain.com/api/v2/login:1 
        
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.

**Comment by taariq** [comment]
Enhanced and updated as per @fullstack412
