### ISSUE TITLE
[BUG] Unable to purchase LightNode _app-a4db3a1c09c6769d.js:374 e ConnectorNotFoundError: Connector not found

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2335]
CHAIN: Arbitrum
Token: USDC

(anonymous) @ _app-a4db3a1c09c6769d.js:374
_app-a4db3a1c09c6769d.js:374 Object Object Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
    at x.onClose (5021.2a7451026a1ac452.js:1:2174)
    at a.<anonymous> (5021.2a7451026a1ac452.js:1:2811)
    at a.emit (_app-a4db3a1c09c6769d.js:374:362371)
    at l.onClose (_app-a4db3a1c09c6769d.js:374:25999)
    at WebSocket.<anonymous> (_app-a4db3a1c09c6769d.js:374:25867)
(anonymous) @ _app-a4db3a1c09c6769d.js:374
_app-a4db3a1c09c6769d.js:374 Object Object Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
    at x.onClose (5021.2a7451026a1ac452.js:1:2174)
    at a.<anonymous> (5021.2a7451026a1ac452.js:1:2811)
    at a.emit (_app-a4db3a1c09c6769d.js:374:362371)
    at l.onClose (_app-a4db3a1c09c6769d.js:374:25999)
    at WebSocket.<anonymous> (_app-a4db3a1c09c6769d.js:374:25867)
(anonymous) @ _app-a4db3a1c09c6769d.js:374
_app-a4db3a1c09c6769d.js:374 Object Object Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
    at x.onClose (5021.2a7451026a1ac452.js:1:2174)
    at a.<anonymous> (5021.2a7451026a1ac452.js:1:2811)
    at a.emit (_app-a4db3a1c09c6769d.js:374:362371)
    at l.onClose (_app-a4db3a1c09c6769d.js:374:25999)
    at WebSocket.<anonymous> (_app-a4db3a1c09c6769d.js:374:25867)
(anonymous) @ _app-a4db3a1c09c6769d.js:374
4690-0410c14d99d6aef2.js:1 args Array(9)
4690-0410c14d99d6aef2.js:1 ethValue 0
4690-0410c14d99d6aef2.js:1 Estimating gas... 586997
4690-0410c14d99d6aef2.js:1 Preparing transaction hash...
_app-a4db3a1c09c6769d.js:374 e ConnectorNotFoundError: Connector not found
    at t9 (_app-a4db3a1c09c6769d.js:378:13130)
    at async buyNow (4690-0410c14d99d6aef2.js:1:18801)
    at async tE (5126-8054fcbe6da0d8b3.js:1:392590)
nodesale.palomachain.com/api/v2/addaddr:1 
        
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)

**Comment by taariq** [comment]
Fixedwit removal of WAGMI
