### ISSUE TITLE
[BUG] Failed to load resource: the server responded with a status of 403. TypeError: Cannot read properties of undefined (reading 'node_sale')

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2363]
OS: Mac
Browser: Chrome

Error:
       Failed to load resource: the server responded with a status of 403 ()
framework-945b357d4a851f4b.js:1 TypeError: Cannot read properties of undefined (reading 'node_sale')
    at g (4690-debf95ec3c7bdb8e.js:1:15458)
    at i7 (5126-144206cd10b2444d.js:1:383671)
    at ad (framework-945b357d4a851f4b.js:1:58499)
    at ud (framework-945b357d4a851f4b.js:1:72829)
    at i (framework-945b357d4a851f4b.js:1:120361)
    at oO (framework-945b357d4a851f4b.js:1:99117)
    at framework-945b357d4a851f4b.js:1:98984
    at oF (framework-945b357d4a851f4b.js:1:98991)
    at ox (framework-945b357d4a851f4b.js:1:95743)
    at oS (framework-945b357d4a851f4b.js:1:94298)
a5 @ framework-945b357d4a851f4b.js:1
main-093f8c685f17391c.js:1 TypeError: Cannot read properties of undefined (reading 'node_sale')
    at g (4690-debf95ec3c7bdb8e.js:1:15458)
    at i7 (5126-144206cd10b2444d.js:1:383671)
    at ad (framework-945b357d4a851f4b.js:1:58499)
    at ud (framework-945b357d4a851f4b.js:1:72829)
    at i (framework-945b357d4a851f4b.js:1:120361)
    at oO (framework-945b357d4a851f4b.js:1:99117)
    at framework-945b357d4a851f4b.js:1:98984
    at oF (framework-945b357d4a851f4b.js:1:98991)
    at ox (framework-945b357d4a851f4b.js:1:95743)
    at oS (framework-945b357d4a851f4b.js:1:94298)
Z @ main-093f8c685f17391c.js:1

Full log
[www.palomachain.com-1730838650724.log](https://github.com/user-attachments/files/17638318/www.palomachain.com-1730838650724.log)

**Comment by taariq** [comment]
Not sure if related to build after blog post https://vercel.com/volume/paloma-website/GXTddmB7rTzXzgtdfzHngV3ENq6z?utm_medium=email&utm_source=notifications&filter=errors

**Comment by taariq** [comment]
Issue resolved.
