### ISSUE TITLE
[BUG] Unable to claim Bonus. (reason="execution reverted: No claimable", method="estimateGas", transaction=)

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2365]
Unable to claim Bonus. (reason="execution reverted: No claimable", method="estimateGas", transaction=

**Address:** 0x83334ef0C6f6396413C508A7762741e9FD8B20E9
**Error:** 
t.<computed> @ _app-18653e12f7e8b9ab.js:374
4690-debf95ec3c7bdb8e.js:1 Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: No claimable", method="estimateGas", transaction={"from":"0x83334ef0C6f6396413C508A7762741e9FD8B20E9","to":"0x2f78AfAdD7E58052c4a8789dc01A1eD49848cc0C","data":"0x4e71d92d","accessList":null}, error={"code":-32603,"message":"execution reverted: No claimable","data":{"originalError":{"message":"execution reverted: No claimable","code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c4e6f20636c61696d61626c650000000000000000000000000000000000000000"}}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at h.makeError (_app-18653e12f7e8b9ab.js:1:456147)
    at h.throwError (_app-18653e12f7e8b9ab.js:1:456261)
    at b (_app-18653e12f7e8b9ab.js:1:530354)
    at f.<anonymous> (_app-18653e12f7e8b9ab.js:1:540215)
    at Generator.throw (<anonymous>)
    at s (_app-18653e12f7e8b9ab.js:1:529471)
claimBonus @ 4690-debf95ec3c7bdb8e.js:1
4690-debf95ec3c7bdb8e.js:1 Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: No claimable", method="estimateGas", transaction={"from":"0x83334ef0C6f6396413C508A7762741e9FD8B20E9","to":"0x2f78AfAdD7E58052c4a8789dc01A1eD49848cc0C","data":"0x4e71d92d","accessList":null}, error={"code":-32603,"message":"execution reverted: No claimable","data":{"originalError":{"message":"execution reverted: No claimable","code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c4e6f20636c61696d61626c650000000000000000000000000000000000000000"}}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at h.makeError (_app-18653e12f7e8b9ab.js:1:456147)
    at h.throwError (_app-18653e12f7e8b9ab.js:1:456261)
    at b (_app-18653e12f7e8b9ab.js:1:530354)
    at f.<anonymous> (_app-18653e12f7e8b9ab.js:1:540215)
    at Generator.throw (<anonymous>)
    at s (_app-18653e12f7e8b9ab.js:1:529471)
claimBonus @ 4690-debf95ec3c7bdb8e.js:1
_app-18653e12f7e8b9ab.js:374 Object Object Error: WebSocket connection closed abnormally with code: 3000 (Unauthorized: origin not allowed)
    at x.onClose (5021.2a7451026a1ac452.js:1:2174)
    at a.<anonymous> (5021.2a7451026a1ac452.js:1:2811)
    at a.emit (_app-18653e12f7e8b9ab.js:374:362371)
    at l.onClose (_app-18653e12f7e8b9ab.js:374:25999)
    at e.onclose (_app-18653e12f7e8b9ab.js:374:25867)

**Comment by taariq** [comment]
Closing. Requires a feature for switching wallet address.
