### ISSUE TITLE
[PALOMABOT] When trying to use llamalend SqueezeBot: SyntaxError: Cannot convert Infinity to a BigIn

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2369]
https://www.palomabot.ai/curve-llamalend/tbtc/ and other bots

_app-dca6f15fbdd20a67.js:1281 Fetch failed loading: GET "https://one.palomachain.com/quote?dst=0x18084fbA666a33d37592fA2633fD49a74DD93a88&src=0xf939e0a03fb07f59a73314e73794be0e57ac1b4e&amount=1000000000000000000&chain=1".
defaultFetchFn @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
fulfilled @ _app-dca6f15fbdd20a67.js:1281
Promise.then
step @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
__async @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
__async @ _app-dca6f15fbdd20a67.js:1281
executeEndpoint @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1
(anonymous) @ _app-dca6f15fbdd20a67.js:1
(anonymous) @ _app-dca6f15fbdd20a67.js:1
(anonymous) @ _app-dca6f15fbdd20a67.js:1
(anonymous) @ _app-dca6f15fbdd20a67.js:1
(anonymous) @ _app-dca6f15fbdd20a67.js:1
(anonymous) @ _app-dca6f15fbdd20a67.js:1
dispatch @ _app-dca6f15fbdd20a67.js:1286
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
Qk @ framework-fee8a7e75612eda8.js:9
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
getCallbackArgs @ 8604-14f2a9034d5fc8bc.js:1
await in getCallbackArgs
getCallbackValues @ 8604-14f2a9034d5fc8bc.js:1
(anonymous) @ [id]-e41d0caf48febe74.js:1
setTimeout
(anonymous) @ [id]-e41d0caf48febe74.js:1
Qj @ framework-fee8a7e75612eda8.js:9
Hk @ framework-fee8a7e75612eda8.js:9
w @ framework-fee8a7e75612eda8.js:9
J @ framework-fee8a7e75612eda8.js:33
R @ framework-fee8a7e75612eda8.js:33
_app-dca6f15fbdd20a67.js:1281 
        
        
       GET https://one.palomachain.com/quote?dst=0x18084fbA666a33d37592fA2633fD49a74DD93a88&src=0xf939e0a03fb07f59a73314e73794be0e57ac1b4e&amount=1000000000000000000&chain=1 403 (Forbidden)
defaultFetchFn @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
fulfilled @ _app-dca6f15fbdd20a67.js:1281
Promise.then
step @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
__async @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
__async @ _app-dca6f15fbdd20a67.js:1281
executeEndpoint @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1
(anonymous) @ _app-dca6f15fbdd20a67.js:1
(anonymous) @ _app-dca6f15fbdd20a67.js:1
(anonymous) @ _app-dca6f15fbdd20a67.js:1
(anonymous) @ _app-dca6f15fbdd20a67.js:1
(anonymous) @ _app-dca6f15fbdd20a67.js:1
(anonymous) @ _app-dca6f15fbdd20a67.js:1
dispatch @ _app-dca6f15fbdd20a67.js:1286
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
(anonymous) @ _app-dca6f15fbdd20a67.js:1
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
Qk @ framework-fee8a7e75612eda8.js:9
(anonymous) @ _app-dca6f15fbdd20a67.js:1281
getCallbackArgs @ 8604-14f2a9034d5fc8bc.js:1
await in getCallbackArgs
getCallbackValues @ 8604-14f2a9034d5fc8bc.js:1
(anonymous) @ [id]-e41d0caf48febe74.js:1
setTimeout
(anonymous) @ [id]-e41d0caf48febe74.js:1
Qj @ framework-fee8a7e75612eda8.js:9
Hk @ framework-fee8a7e75612eda8.js:9
w @ framework-fee8a7e75612eda8.js:9
J @ framework-fee8a7e75612eda8.js:33
R @ framework-fee8a7e75612eda8.js:33
_app-dca6f15fbdd20a67.js:6944 Uncaught (in promise) SyntaxError: Cannot convert Infinity to a BigInt (at _app-dca6f15fbdd20a67.js:6944:40397)
    at BigInt (<anonymous>)
    at numberToHex (_app-dca6f15fbdd20a67.js:6944:40397)
    at signed (_app-dca6f15fbdd20a67.js:6944:26329)
    at prepareParam (_app-dca6f15fbdd20a67.js:6944:26354)
    at es.params (_app-dca6f15fbdd20a67.js:6944:27144)
    at encodeAbiParameters (_app-dca6f15fbdd20a67.js:6944:27184)
    at encodeFunctionData (_app-dca6f15fbdd20a67.js:6944:28712)
    at readContract (_app-dca6f15fbdd20a67.js:1311:112543)
    at Object.readContract (_app-dca6f15fbdd20a67.js:1312:7284)
    at chunk_TSH6VVF4_readContract (_app-dca6f15fbdd20a67.js:1315:15499)
numberToHex @ _app-dca6f15fbdd20a67.js:6944
signed @ _app-dca6f15fbdd20a67.js:6944
prepareParam @ _app-dca6f15fbdd20a67.js:6944
es.params @ _app-dca6f15fbdd20a67.js:6944
encodeAbiParameters @ _app-dca6f15fbdd20a67.js:6944
encodeFunctionData @ _app-dca6f15fbdd20a67.js:6944
readContract @ _app-dca6f15fbdd20a67.js:1311
readContract @ _app-dca6f15fbdd20a67.js:1312
chunk_TSH6VVF4_readContract @ _app-dca6f15fbdd20a67.js:1315
getCallbackArgs @ 8604-14f2a9034d5fc8bc.js:1
setTimeout
(anonymous) @ [id]-e41d0caf48febe74.js:1
Qj @ framework-fee8a7e75612eda8.js:9
Hk @ framework-fee8a7e75612eda8.js:9
w @ framework-fee8a7e75612eda8.js:9
J @ framework-fee8a7e75612eda8.js:33
R @ framework-fee8a7e75612eda8.js:33

**Comment by taariq** [comment]
Closing as wont' fix.
