### ISSUE TITLE
get high returns: pancakeswap returns no results

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#237]
https://momentumbots.palomachain.com/?dex=pancakeswap_new&lag_return=0&daily_volume=0&vol_30=0&market_cap=0
https://momentumbots.palomachain.com/?dex=biswap&lag_return=0&daily_volume=0&vol_30=0&market_cap=0

return no results. All other DEX listed here https://github.com/VolumeFi/paloma/issues/223 do. 

Error:

```
 Traceback (most recent call last):
   File "/root/.cache/pypoetry/virtualenvs/trading-bots-Fx44JTns-py3.10/lib/python3.10/site-packages/bottle.py", line 876, in _handle
     return route.call(**args)
   File "/root/.cache/pypoetry/virtualenvs/trading-bots-Fx44JTns-py3.10/lib/python3.10/site-packages/sentry_sdk/integrations/bottle.py", line 140, in wrapped_callback
     raise exception
   File "/root/.cache/pypoetry/virtualenvs/trading-bots-Fx44JTns-py3.10/lib/python3.10/site-packages/sentry_sdk/integrations/bottle.py", line 130, in wrapped_callback
     res = prepared_callback(*args, **kwargs)
   File "/root/.cache/pypoetry/virtualenvs/trading-bots-Fx44JTns-py3.10/lib/python3.10/site-packages/bottle.py", line 1759, in wrapper
     rv = callback(*a, **ka)
   File "/root/app/momentum_cache_refresh/app.py", line 29, in get_high_returns
     df = momentum_scanner_intraday.get_high_returns(
   File "/root/app/momentum_cache_refresh/momentum_scanner_intraday.py", line 73, in get_high_returns
     vols = gecko.exchanges(dex)
   File "/root/app/momentum_cache_refresh/gecko.py", line 47, in exchanges
     for ticker in get("exchanges", dex)["tickers"]
 KeyError: 'tickers'
```

**Comment by verabehr** [comment]
as discussed - removed `biswap`

on 6:27am 5/24 https://momentumbots.palomachain.com/?dex=uniswap_v2&lag_return=6&daily_volume=0&vol_30=1&market_cap=1 also returned `{"reason":{}}`
