### ISSUE TITLE
dca bot not working

### ISSUE THREAD

**Issue by rootedbox** [VolumeFi/paloma#375]
python3 ./bot_execute.py
Traceback (most recent call last):
  File "/home/rootedbox/app/dca_bot_python_script_pancakeswap/./bot_execute.py", line 150, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/rootedbox/app/dca_bot_python_script_pancakeswap/./bot_execute.py", line 145, in main
    await pancakeswap_bot(network)
  File "/home/rootedbox/app/dca_bot_python_script_pancakeswap/./bot_execute.py", line 52, in pancakeswap_bot
    CON.execute("CREATE INDEX IF NOT EXISTS swap_idx ON deposits (swap_id);")
sqlite3.OperationalError: no such column: swap_id
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f1567b9beb0>

**Comment by taariq** [comment]
@webelf101 status on this?

**Comment by taariq** [comment]
Fixed.
