### ISSUE TITLE
Update DB for DCA bot and set up service

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#383]
### Background
DCA bot uses different columns compared to the other bots we already have live. The required columns are here https://github.com/VolumeFi/dca_bot_python_script/blob/main/bot_execute.py#L40-L51

### Done when

- [ ] DCA bot service is set up on server
- [ ] service api includes the DCA records

**Comment by rootedbox** [comment]
getting the following when trying to run

```
Traceback (most recent call last):
  File "/home/rootedbox/app/dca_bot_python_script/bot_execute.py", line 150, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/rootedbox/app/dca_bot_python_script/bot_execute.py", line 145, in main
    await pancakeswap_bot(network)
  File "/home/rootedbox/app/dca_bot_python_script/bot_execute.py", line 56, in pancakeswap_bot
    res = CON.execute("SELECT * FROM fetched_blocks WHERE network_name = ? \
TypeError: execute expected at most 2 arguments, got 3
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f1f1cb87e80>
```

when trying to run..  I've created the following shell script to run everything

run.sh
```
#! /bin/sh
export PALOMA_KEY='fancy clinic exotic cactus budget duty street bag extra supply evoke shield swing job rail predict brisk orbit road cargo child swing wheat element' # paloma account mnemonic phrase'
export PALOMA_LCD=https://lcd.palomachain.com
export PALOMA_CHAIN_ID=messenger
export CODE_ID=11

python3 bot_execute.py
```


it's currently running from `/home/rootedbox/app/dca_bot_python_script` as rootedbox on ssh nest-service.palomachain.com

**Comment by rootedbox** [comment]
please look at this @webelf101
