### ISSUE TITLE
Set up Curve DCA bot server

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#506]
details here https://www.notion.so/volumefi/Palomabot-repo-and-contract-address-inventory-73691914623c4e91a0972ef6f13aad98?pvs=4

### Done when

- [ ] script is running on the server
- [ ] Curve DCA bot is returned in service api

**Comment by rootedbox** [comment]
@webelf101 getting the following when trying to run

```
Traceback (most recent call last):
  File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 197, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 192, in main
    await curve_bot(network)
  File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 67, in curve_bot
    dca_sc: Contract = w3.eth.contract(
  File "/home/rootedbox/.local/lib/python3.10/site-packages/web3/eth.py", line 958, in contract
    return ContractFactory(address)
  File "/home/rootedbox/.local/lib/python3.10/site-packages/web3/contract.py", line 338, in __init__
    self.address = normalize_address(self.web3.ens, address)
  File "/home/rootedbox/.local/lib/python3.10/site-packages/web3/_utils/normalizers.py", line 252, in normalize_address
    validate_address(address)
  File "/home/rootedbox/.local/lib/python3.10/site-packages/web3/_utils/validation.py", line 182, in validate_address
    raise InvalidAddress(
web3.exceptions.InvalidAddress: ('Web3.py only accepts checksum addresses. The software that gave you this non-checksum address should be considered unsafe, please file it as a bug on their platform. Try using an ENS name instead. Or, if you must accept lower safety, use Web3.toChecksumAddress(lower_case_address).', '0xd02d8b2c72cd13fb73cdfe28aa37aeba04ed19e6')
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9fd8aa6920>

```

can you double check the networks.json too make sure it's ok. 
its installed in `/home/rootedbox/app/curve-dca-bot-script` on ` nest-service.palomachain.com`

**Comment by rootedbox** [comment]
@verabehr we are all setup and ready to be run as a service.. that being said we are having issues running the code.. see above.

**Comment by webelf101** [comment]
I updated the env and networks.json.

**Comment by rootedbox** [comment]
```
nano ./run.sh
./run.sh
Traceback (most recent call last):
  File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 199, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 194, in main
    await curve_bot(network)
  File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 103, in curve_bot
    CON.execute(
sqlite3.OperationalError: 13 values for 12 columns
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f208aeaebf0>
```

@webelf101 still not working seems to have something off with your sql.. please test after any changes.  cc: @verabehr @taariq

**Comment by taariq** [comment]
@webelf101 Please provide a response today. We need this before MONDAY.

**Comment by webelf101** [comment]
I fixed the issue and pushed it. Please let me know when you have the other blockers. @rootedbox

**Comment by taariq** [comment]
@webelf101 for tracking, will you please add the commit that updated that change? The more people who are aware of your edits, the better for understanding failure issues.

**Comment by taariq** [comment]
@webelf101 I got it. https://github.com/VolumeFi/curve-dca-bot-script/commit/a665f3de2d32d975472bcb5a544dfcae44aa3ddc is here. sql value bug

**Comment by rootedbox** [comment]
@webelf101 it seems to work is this expected output?


```
./run.sh
An error occurred: execution reverted
/home/rootedbox/app/curve-dca-bot-script/bot_execute.py:194: RuntimeWarning: coroutine 'curve_bot.<locals>.inner' was never awaited
  await curve_bot(network)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Skipping duplicate entry: (0, '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE', '0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E', 5000000000000000, '0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432', 2, 2, 7200, 1689804755, 'ETH', 'curve', 'dca')
An error occurred: execution reverted
Skipping duplicate entry: (0, '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE', '0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E', 5000000000000000, '0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432', 2, 2, 7200, 1689804755, 'ETH', 'curve', 'dca')
An error occurred: execution reverted
```

**Comment by webelf101** [comment]
https://github.com/VolumeFi/curve-dca-bot-script/commit/e37fe135e2447e2f1bcd0ec86a13d2456f9685b9
There wasn't fetched block table update. I added it.

**Comment by webelf101** [comment]
https://github.com/VolumeFi/curve-dca-bot-script/commit/e37fe135e2447e2f1bcd0ec86a13d2456f9685b9
There wasn't fetched block table update. I added it. @rootedbox

**Comment by taariq** [comment]
Thank you @webelf101. Okay. Curve DCA bot is coming! Nearly there!

**Comment by rootedbox** [comment]
same result

```
./run.sh
Skipping duplicate entry: (0, '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE', '0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E', 5000000000000000, '0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432', 2, 2, 7200, 1689804755, 'ETH', 'curve', 'dca')
An error occurred: execution reverted
/home/rootedbox/app/curve-dca-bot-script/bot_execute.py:199: RuntimeWarning: coroutine 'curve_bot.<locals>.inner' was never awaited
  await curve_bot(network)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Skipping duplicate entry: (0, '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE', '0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E', 5000000000000000, '0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432', 2, 2, 7200, 1689804755, 'ETH', 'curve', 'dca')
```

@webelf101 please qa on its installed in /home/rootedbox/app/curve-dca-bot-script on  nest-service.palomachain.com before bouncing back

**Comment by taariq** [comment]
@webelf101 Will you update this before standup today? We lost a day with this bug.

**Comment by rootedbox** [comment]
setup to run every minute on server
