### ISSUE TITLE
Multiple SQL Bugs in Curve DCA Bot

### ISSUE THREAD

**Issue by rootedbox** [VolumeFi/paloma#581]
multiple sql bug see below.

```
Jul 31 22:24:41 snapshot run.sh[2173954]: OverflowError: Python int too large to convert to SQLite INTEGER
Jul 31 22:24:41 snapshot run.sh[2173954]: Unclosed client session
Jul 31 22:24:41 snapshot run.sh[2173954]: client_session: <aiohttp.client.ClientSession object at 0x7f2e5e397f40>
Jul 31 22:24:41 snapshot systemd[1]: curve-dca-bot-service.service: Main process exited, code=exited, status=1/FAILURE
Jul 31 22:24:41 snapshot systemd[1]: curve-dca-bot-service.service: Failed with result 'exit-code'.
Jul 31 22:24:41 snapshot systemd[1]: curve-dca-bot-service.service: Consumed 1.045s CPU time.
Jul 31 22:24:42 snapshot start.sh[263161]: [Error: SQLITE_ERROR: no such column: tracking_price2] {
Jul 31 22:24:42 snapshot start.sh[263161]:   errno: 1,
Jul 31 22:24:42 snapshot start.sh[263161]:   code: 'SQLITE_ERROR'
Jul 31 22:24:42 snapshot start.sh[263161]: }
```

**Comment by taariq** [comment]
Related to my DCA bot created here: https://etherscan.io/tx/0x00322187c9ac9cb6d9423adf6e3633fda60bd545532853d5cfb30eb78f1aa60c

**Comment by verabehr** [comment]
code pushed, server needs to be updated

**Comment by verabehr** [comment]
https://github.com/VolumeFi/curve-dca-bot-script/pull/8

**Comment by verabehr** [comment]
the updated curve-dca-bot-script is dying on this line ```BLOCK_NUMBER: int = int(w3.eth.get_block_number()) with the following error requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb23abdd450>```

**Comment by taariq** [comment]
@webelf101 have you updated contracts? I'd like to close this today.

**Comment by verabehr** [comment]
blocked by messenger relay

**Comment by verabehr** [comment]
relaying is functioning again

**Comment by verabehr** [comment]
this is presumably fixed but testing is blocked by https://github.com/VolumeFi/paloma/issues/634

**Comment by verabehr** [comment]
```Aug 10 20:16:26 bots-server run.sh[2344177]: Unclosed client session
Aug 10 20:16:26 bots-server run.sh[2344177]: client_session: <aiohttp.client.ClientSession object at 0x7f637afd50c0>
Aug 10 20:16:33 bots-server run.sh[2344522]: Traceback (most recent call last):
Aug 10 20:16:33 bots-server run.sh[2344522]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 286, in <module>
Aug 10 20:16:33 bots-server run.sh[2344522]:     asyncio.run(main())
Aug 10 20:16:33 bots-server run.sh[2344522]:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
Aug 10 20:16:33 bots-server run.sh[2344522]:     return loop.run_until_complete(main)
Aug 10 20:16:33 bots-server run.sh[2344522]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
Aug 10 20:16:33 bots-server run.sh[2344522]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 278, in main
Aug 10 20:16:33 bots-server run.sh[2344522]:     await curve_bot(network)
Aug 10 20:16:33 bots-server run.sh[2344522]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 213, in curve_bot
Aug 10 20:16:33 bots-server run.sh[2344522]:     deposits.append({"deposit_id": str(deposit_id), "amount_out_min": str(int(amount_out_min[i]) * (DENOMINATOR - SLIPPAGE) / DENOMINATOR)})
Aug 10 20:16:33 bots-server run.sh[2344522]: TypeError: unsupported operand type(s) for -: 'int' and 'str'
Aug 10 20:16:33 bots-server run.sh[2344522]: Unclosed client session
Aug 10 20:16:33 bots-server run.sh[2344522]: client_session: <aiohttp.client.ClientSession object at 0x7f11769cd090>
Aug 10 20:16:39 bots-server run.sh[2344561]: Traceback (most recent call last):
Aug 10 20:16:39 bots-server run.sh[2344561]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 286, in <module>
Aug 10 20:16:39 bots-server run.sh[2344561]:     asyncio.run(main())
Aug 10 20:16:39 bots-server run.sh[2344561]:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
Aug 10 20:16:39 bots-server run.sh[2344561]:     return loop.run_until_complete(main)
Aug 10 20:16:39 bots-server run.sh[2344561]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
Aug 10 20:16:39 bots-server run.sh[2344561]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 278, in main
Aug 10 20:16:39 bots-server run.sh[2344561]:     await curve_bot(network)
Aug 10 20:16:39 bots-server run.sh[2344561]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 213, in curve_bot
Aug 10 20:16:39 bots-server run.sh[2344561]:     deposits.append({"deposit_id": str(deposit_id), "amount_out_min": str(int(amount_out_min[i]) * (DENOMINATOR - SLIPPAGE) / DENOMINATOR)})
Aug 10 20:16:39 bots-server run.sh[2344561]: TypeError: unsupported operand type(s) for -: 'int' and 'str'
Aug 10 20:16:39 bots-server run.sh[2344561]: Unclosed client session
Aug 10 20:16:39 bots-server run.sh[2344561]: client_session: <aiohttp.client.ClientSession object at 0x7fb60a1e1030>
Aug 10 20:16:45 bots-server run.sh[2345171]: Traceback (most recent call last):
Aug 10 20:16:45 bots-server run.sh[2345171]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 286, in <module>
Aug 10 20:16:45 bots-server run.sh[2345171]:     asyncio.run(main())
Aug 10 20:16:45 bots-server run.sh[2345171]:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
Aug 10 20:16:45 bots-server run.sh[2345171]:     return loop.run_until_complete(main)
Aug 10 20:16:45 bots-server run.sh[2345171]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
Aug 10 20:16:45 bots-server run.sh[2345171]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 278, in main
Aug 10 2```

**Comment by verabehr** [comment]
new errors

```Aug 10 21:15:48 bots-server run.sh[2497564]: Traceback (most recent call last):
Aug 10 21:15:48 bots-server run.sh[2497564]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 286, in <module>
Aug 10 21:15:48 bots-server run.sh[2497564]:     asyncio.run(main())
Aug 10 21:15:48 bots-server run.sh[2497564]:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
Aug 10 21:15:48 bots-server run.sh[2497564]:     return loop.run_until_complete(main)
Aug 10 21:15:48 bots-server run.sh[2497564]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
Aug 10 21:15:48 bots-server run.sh[2497564]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 278, in main
Aug 10 21:15:48 bots-server run.sh[2497564]:     await curve_bot(network)
Aug 10 21:15:48 bots-server run.sh[2497564]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 215, in curve_bot
Aug 10 21:15:48 bots-server run.sh[2497564]:     tx = await WALLET.create_and_sign_tx(CreateTxOptions(msgs=[
Aug 10 21:15:48 bots-server run.sh[2497564]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/wallet.py", line 46, in create_and_sign_tx
Aug 10 21:15:48 bots-server run.sh[2497564]:     res = await self.account_number_and_sequence()
Aug 10 21:15:48 bots-server run.sh[2497564]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/wallet.py", line 26, in account_number_and_sequence
Aug 10 21:15:48 bots-server run.sh[2497564]:     res = await self.lcd.auth.account_info(self.key.acc_address)
Aug 10 21:15:48 bots-server run.sh[2497564]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/api/auth.py", line 33, in account_info
Aug 10 21:15:48 bots-server run.sh[2497564]:     result = await self._c._get(f"/cosmos/auth/v1beta1/accounts/{address}", params)
Aug 10 21:15:48 bots-server run.sh[2497564]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/lcdclient.py", line 111, in _get
Aug 10 21:15:48 bots-server run.sh[2497564]:     async with self.session.get(
Aug 10 21:15:48 bots-server run.sh[2497564]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
Aug 10 21:15:48 bots-server run.sh[2497564]:     self._resp = await self._coro
Aug 10 21:15:48 bots-server run.sh[2497564]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/aiohttp/client.py", line 467, in _request
Aug 10 21:15:48 bots-server run.sh[2497564]:     with timer:
Aug 10 21:15:48 bots-server run.sh[2497564]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/aiohttp/helpers.py", line 700, in __enter__
Aug 10 21:15:48 bots-server run.sh[2497564]:     raise RuntimeError(
Aug 10 21:15:48 bots-server run.sh[2497564]: RuntimeError: Timeout context manager should be used inside a task
Aug 10 21:15:48 bots-server run.sh[2497564]: Unclosed client session
Aug 10 21:15:48 bots-server run.sh[2497564]: client_session: <aiohttp.client.ClientSession object at 0x7ff9269e10c0>
Aug 10 21:15:55 bots-server run.sh[2497602]: https://lcd.palomachain.com/cosmos/auth/v1beta1/accounts/paloma10dry4t7gr8rhd0khqcqyq95ytdh6vs8sjv84yj
Aug 10 21:15:55 bots-server run.sh[2497602]: Traceback (most recent call last):
Aug 10 21:15:55 bots-server run.sh[2497602]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 286, in <module>
Aug 10 21:15:55 bots-server run.sh[2497602]:     asyncio.run(main())
Aug 10 21:15:55 bots-server run.sh[2497602]:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
Aug 10 21:15:55 bots-server run.sh[2497602]:     return loop.run_until_complete(main)
Aug 10 21:15:55 bots-server run.sh[2497602]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
Aug 10 21:15:55 bots-server run.sh[2497602]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 278, in main
Aug 10 21:15:55 bots-server run.sh[2497602]:     await curve_bot(network)
Aug 10 21:15:55 bots-server run.sh[2497602]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 215, in curve_bot
Aug 10 21:15:55 bots-server run.sh[2497602]:     tx = await WALLET.create_and_sign_tx(CreateTxOptions(msgs=[
Aug 10 21:15:55 bots-server run.sh[2497602]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/wallet.py", line 46, in create_and_sign_tx
Aug 10 21:15:55 bots-server run.sh[2497602]:     res = await self.account_number_and_sequence()
Aug 10 21:15:55 bots-server run.sh[2497602]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/wallet.py", line 26, in account_number_and_sequence
Aug 10 21:15:55 bots-server run.sh[2497602]:     res = await self.lcd.auth.account_info(self.key.acc_address)
Aug 10 21:15:55 bots-server run.sh[2497602]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/api/auth.py", line 33, in account_info
Aug 10 21:15:55 bots-server run.sh[2497602]:     result = await self._c._get(f"/cosmos/auth/v1beta1/accounts/{address}", params)
Aug 10 21:15:55 bots-server run.sh[2497602]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/paloma_sdk/client/lcd/lcdclient.py", line 111, in _get
Aug 10 21:15:55 bots-server run.sh[2497602]:     async with self.session.get(
Aug 10 21:15:55 bots-server run.sh[2497602]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
Aug 10 21:15:55 bots-server run.sh[2497602]:     self._resp = await self._coro
Aug 10 21:15:55 bots-server run.sh[2497602]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/aiohttp/client.py", line 467, in _request
Aug 10 21:15:55 bots-server run.sh[2497602]:     with timer:
Aug 10 21:15:55 bots-server run.sh[2497602]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/aiohttp/helpers.py", line 700, in __enter__
Aug 10 21:15:55 bots-server run.sh[2497602]:     raise RuntimeError(```

**Comment by webelf101** [comment]
I fixed the bug. Please check again. @verabehr

**Comment by verabehr** [comment]
Confirming this works now @webelf101 👏
