### ISSUE TITLE
Make vote distribution bot run as a service

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#647]

**Comment by rootedbox** [comment]
@wc117 I've made some changes to https://github.com/VolumeFi/vote-distribution-bot-script so that we can run it as a service instead of as a cron job. I haven't touched the main part of the scripts and they seem to be having issues..

please check the changes I made yesterday. https://github.com/VolumeFi/vote-distribution-bot-script/commits/master


Currently the error we are getting is the following

```
Running vote distribution bot vote...
Running vote distribution bot collect...
Traceback (most recent call last):
  File "/home/rootedbox/app/vote-distribution-bot-script/vote_distribution.py", line 30, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/rootedbox/app/vote-distribution-bot-script/vote_distribution.py", line 20, in main
    await collect_module.run_collect()
  File "/home/rootedbox/app/vote-distribution-bot-script/vote_distribution_bot_collect.py", line 81, in run_collect
    data = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 28 column 1 (char 678)
```

Please check and fix the code. It's currently running on bots-server in the following directory /home/rootedbox/app/vote-distribution-bot-script

**Comment by wc117** [comment]
I fixed it. Please check again. @rootedbox
