### ISSUE TITLE
BUG: Curve TWAP Bot Fails to run ValueError: {'code': -32015, 'message': 'VM execution error.', 'data': 'revert'}

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#703]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

```
Aug 26 22:40:14 bots-server systemd[1]: Started dca robot  service.
Aug 26 22:40:47 bots-server run.sh[1366632]: Traceback (most recent call last):
Aug 26 22:40:47 bots-server run.sh[1366632]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 369, in <module>
Aug 26 22:40:47 bots-server run.sh[1366632]:     asyncio.run(main())
Aug 26 22:40:47 bots-server run.sh[1366632]:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
Aug 26 22:40:47 bots-server run.sh[1366632]:     return loop.run_until_complete(main)
Aug 26 22:40:47 bots-server run.sh[1366632]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
Aug 26 22:40:47 bots-server run.sh[1366632]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 361, in main
Aug 26 22:40:47 bots-server run.sh[1366632]:     await curve_bot(network)
Aug 26 22:40:47 bots-server run.sh[1366632]:   File "/home/rootedbox/app/curve-dca-bot-script/bot_execute.py", line 292, in curve_bot
Aug 26 22:40:47 bots-server run.sh[1366632]:     amount_out_min = dca_sc.functions.multiple_swap_view(deposit_ids, remaining_countlist).call()
Aug 26 22:40:47 bots-server run.sh[1366632]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/web3/contract.py", line 970, in call
Aug 26 22:40:47 bots-server run.sh[1366632]:     return call_contract_function(
Aug 26 22:40:47 bots-server run.sh[1366632]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/web3/contract.py", line 1525, in call_contract_function
Aug 26 22:40:47 bots-server run.sh[1366632]:     return_data = web3.eth.call(
Aug 26 22:40:47 bots-server run.sh[1366632]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/web3/module.py", line 57, in caller
Aug 26 22:40:47 bots-server run.sh[1366632]:     result = w3.manager.request_blocking(method_str,
Aug 26 22:40:47 bots-server run.sh[1366632]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
Aug 26 22:40:47 bots-server run.sh[1366632]:     return self.formatted_response(response,
Aug 26 22:40:47 bots-server run.sh[1366632]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/web3/manager.py", line 171, in formatted_response
Aug 26 22:40:47 bots-server run.sh[1366632]:     raise ValueError(response["error"])
Aug 26 22:40:47 bots-server run.sh[1366632]: ValueError: {'code': -32015, 'message': 'VM execution error.', 'data': 'revert'}
Aug 26 22:40:47 bots-server run.sh[1366632]: Unclosed client session
Aug 26 22:40:47 bots-server run.sh[1366632]: client_session: <aiohttp.client.ClientSession object at 0x7fb55b9f0910>
```

with the following settings:
```
    "ADDRESS": "0x6eA64066ef9Fa9Efaf2E98bE2db5Ef9f3F8355C5",,
    "JOB_ID": "curvedcabotjob05",
    "CHAIN_TYPE": "evm",
    "CHAIN_REFERENCE_ID": "eth-main",
    "COINGECKO_CHAIN_ID": "ethereum",
    "NETWORK_NAME": "ETH",
    "FROM_BLOCK":17919285,
    "CW": "paloma1emjm9l2djylv5re0cx0nujp5xv645qe8rp4hwxzme42wpkjvs8xsdu3s5y",
    "DEX": "curve"
  }
```

**Comment by taariq** [comment]
Synopsis from @webelf101: 

Single step swap was successful. But multiple step swap wasn't successful. There aren't any differences between multiple step swap and single step swap in the function call to the Curve protocol.
And we don't have any error messages in the logs.
Potential issues we are thinking are as follows:

1. Errors in managing swap route and swap params, and pools parameters in the twap bot contract.
2. Errors in building parameters from UI.

We think the errors might be from either of these two issues.
Otherwise, they might not be wrong and there might be some errors in the other part we don't know.
We are going to simulate the trading with testing framework and find the exact issue.

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/curve-twap-bot-script/pull/25
