### ISSUE TITLE
BUG: UNIQUE constraint failed

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#978]
the script fails on this deposit https://etherscan.io/tx/0xf874625186ba9f22709dd8bd5b8b571cef6f2ccaaffcf1fa899a90e5bd00ca59

```
Nov 10 19:31:17 bots-server npm[2854197]: stdout: Attempt 1 failed with error: UNIQUE constraint failed: deposits.deposit_id, deposits.network_name, deposits.bot, deposits.contract
Nov 10 19:31:17 bots-server npm[2854197]: Attempt 2 failed with error: UNIQUE constraint failed: deposits.deposit_id, deposits.network_name, deposits.bot, deposits.contract
Nov 10 19:31:17 bots-server npm[2854197]: Attempt 3 failed with error: UNIQUE constraint failed: deposits.deposit_id, deposits.network_name, deposits.bot, deposits.contract
Nov 10 19:31:17 bots-server npm[2854197]: Attempt 4 failed with error: UNIQUE constraint failed: deposits.deposit_id, deposits.network_name, deposits.bot, deposits.contract
Nov 10 19:31:17 bots-server npm[2854197]: Attempt 5 failed with error: UNIQUE constraint failed: deposits.deposit_id, deposits.network_name, deposits.bot, deposits.contract
Nov 10 19:31:17 bots-server npm[2854197]: stderr: Traceback (most recent call last):
Nov 10 19:31:17 bots-server npm[2854197]:   File "/home/rootedbox/app/offramp-eure-bot-script/./bot-execute.py", line 227, in <module>
Nov 10 19:31:17 bots-server npm[2854197]: stderr:     asyncio.run(main())
Nov 10 19:31:17 bots-server npm[2854197]:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
Nov 10 19:31:17 bots-server npm[2854197]:     return loop.run_until_complete(main)
Nov 10 19:31:17 bots-server npm[2854197]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
Nov 10 19:31:17 bots-server npm[2854197]:   File "/home/rootedbox/app/offramp-eure-bot-script/./bot-execute.py", line 222, in main
Nov 10 19:31:17 bots-server npm[2854197]: stderr:     await eure_bot(network)
Nov 10 19:31:17 bots-server npm[2854197]:   File "/home/rootedbox/app/offramp-eure-bot-script/./bot-execute.py", line 121, in eure_bot
Nov 10 19:31:17 bots-server npm[2854197]: stderr:     execute_with_retry(query)
Nov 10 19:31:17 bots-server npm[2854197]:   File "/home/rootedbox/app/offramp-eure-bot-script/./bot-execute.py", line 49, in execute_with_retry
Nov 10 19:31:17 bots-server npm[2854197]:     raise Exception(f"Failed to execute query after {max_attempts} attempts")
Nov 10 19:31:17 bots-server npm[2854197]: stderr: Exception: Failed to execute query after 5 attempts
Nov 10 19:31:17 bots-server npm[2854197]: stderr: Unclosed client session
Nov 10 19:31:17 bots-server npm[2854197]: client_session: <aiohttp.client.ClientSession object at 0x7f7fa58aa620>
Nov 10 19:31:17 bots-server npm[2854197]: bot-execute.py script exited with code 1
Nov 10 19:32:17 bots-server npm[2854197]: stdout: Skipping duplicate entry: (4, '0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E', '0x6B175474E89094C44Da98b954EedeAC495271d0F', '42561165493095589208', '425071>
Nov 10 19:32:17 bots-server npm[2854197]: Attempt 1 failed with error: UNIQUE constraint failed: deposits.deposit_id, deposits.network_name, deposits.bot, deposits.contract
Nov 10 19:32:17 bots-server npm[2854197]: Attempt 2 failed with error: UNIQUE constraint failed: deposits.deposit_id, deposits.network_name, deposits.bot, deposits.contract
Nov 10 19:32:17 bots-server npm[2854197]: Attempt 3 failed with error: UNIQUE constraint failed: deposits.deposit_id, deposits.network_name, deposits.bot, deposits.contract
Nov 10 19:32:17 bots-server npm[2854197]: Attempt 4 failed with error: UNIQUE constraint failed: deposits.deposit_id, deposits.network_name, deposits.bot, deposits.contract
Nov 10 19:32:17 bots-server npm[2854197]: Attempt 5 failed with error: UNIQUE constraint failed: deposits.deposit_id, deposits.network_name, deposits.bot, deposits.contract
Nov 10 19:32:17 bots-server npm[2854197]: stderr: Traceback (most recent call last):
Nov 10 19:32:17 bots-server npm[2854197]: stderr:   File "/home/rootedbox/app/offramp-eure-bot-script/./bot-execute.py", line 227, in <module>
Nov 10 19:32:17 bots-server npm[2854197]: stderr:     asyncio.run(main())
Nov 10 19:32:17 bots-server npm[2854197]: stderr:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
Nov 10 19:32:17 bots-server npm[2854197]: stderr:     return loop.run_until_complete(main)
Nov 10 19:32:17 bots-server npm[2854197]: stderr:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
Nov 10 19:32:17 bots-server npm[2854197]: stderr:   File "/home/rootedbox/app/offramp-eure-bot-script/./bot-execute.py", line 222, in main
Nov 10 19:32:17 bots-server npm[2854197]: stderr:     await eure_bot(network)
```

**Comment by rootedbox** [comment]
https://github.com/VolumeFi/offramp-eure-bot-script/commit/ad29559e7df7362f1541c9c1914e9e34bdfc734b
https://github.com/VolumeFi/offramp-eure-bot-script/commit/0aa4b98acf7eb48c93349a2c60ebd36370d1ed99
